#!/usr/bin/perl
#use strict;
#use warnings;
use File::Basename;
use Getopt::Long;
my %len = (
"AAAAAAAATTAGCCGGAC_GGGGGCATCTCTTATACT"=>"D3S1358_pool1",
"GATCCTATAAGGTAGAGT_TAGGACAGATGATAAATA"=>"vWA_pool1",
"CAAGTGCCAGATGCTCGT_TGTGTGTGCATCTGTAAG"=>"D16S539_pool1",
"GTGTTCCAACCTGAGTCT_CATTTCCTGTGTCAGACC"=>"CSF1PO_pool1",
"GCTCTCACAACCCCCACC_CTTCTGTCCTTGTCAGCG"=>"TPOX_pool1",
"GATCCTTGGGGTGTCGCT_GTATCCCATTGCGTGAAT"=>"D8S1179_pool1",
"GATTCTTCAGCTTGTAGA_AGAGACAGACTAATAGGA"=>"D21S11_pool1",
"TAGTCTCAGCTACTTGCA_GTGGAGATGTCTTACAAT"=>"D18S51_pool1",
"TAAGACCCACGGCCAGAA_TTAAATTGGAGCTAAGTG"=>"D2S441_pool1",
"ATAGGTTTTTAAGGAACA_AGGTTGAGGCTGCAAAAA"=>"D19S433_pool1",
"ACTGCTACAACTCACACC_ATTCCCATTGGCCTGTTC"=>"TH01_pool1",
"CCCATAGGTTTTGAACTC_TGCTGAGTGATTTGTCTG"=>"FGA_pool1",
"GGGGTCCAGGATGCTGAT_TGAGTGATCACGCGAATG"=>"D22S1045_pool1",
"TTAAAGCTTCTAATTAAA_ATTCCAATCATAGCCACA"=>"D5S818_pool1",
"ACAAATGGTAATTCTGCC_CAGCCCAAAAAGACAGAC"=>"D13S317_pool1",
"CAGGCATGTGCTACTGCA_CCTCATTGACAGAATTGC"=>"D7S820_pool1",
"TCAGGAATAAGTGCAGTG_AAAGCAAACCTGAGCATT"=>"D10S1248_pool1",
"TGGGTCATTGTAAAGGTC_CTGTGTTAGTCAGGATTC"=>"D1S1656_pool1",
"AACTCAAATTGTGATAGT_CCTCCATATCACTTGAGC"=>"D12S391_pool1",
"GGAGCTCTCACCAGGGGG_TGGCCCATAATCATGAGT"=>"D2S1338_pool1",
"AGGCACTTCATATTCATA_CCATAATTGTATGAGCCA"=>"D6S1043_pool1",
"GGAGGCTGAAACAGGAGA_TTGATACATGGAAAGAAT"=>"PentaE_pool1",
"GAGCCTGGAAGGTCGAAG_GCCTAACCTATGGTCATA"=>"PentaD_pool1",
#"CGCGGTGTAAGGAGGTTT_CTCCGTCAAAAGAAAGAA"=>"SE33_pool1",
"GTCTCTCTTAATGTTAAC_GTAGGAACTGTAAAATTG"=>"Ame_pool1",
"CCCCACCACAGATTAGCA_CCATAGAGGGATAGGTAG"=>"DYS391_pool1",
"GCCTCCCAGCCTACATCT_AACTCAGCCCAAAACTTC"=>"DYS456_pool1",
"ATCATACATGTTTCAGAA_GCAATGTGTATACTCAGA"=>"DYS390_pool1",
"TATCCCTGAGTAGCAGAA_TGTATCCAACTCTCATCT"=>"DYS389I-II_pool1",
"CAGCTGCCTCTAATGTGA_AGTTCTGGCATTACAAGC"=>"DYS458_pool1",
"AATTTGCTGGTCAATCTC_ACTATGACTACTGAGTTT"=>"DYS19_pool1",
"AGAGCTAGACACCATGCC_AAAATAATCTATCTATTC"=>"DYS385a/b_pool1",
"GTATGTCTTTACTAGCAG_GGCCTATAATCTAACTAA"=>"DYS393_pool1",
"CTATGTCCTGAATGGTAC_CTGGCTTGGAATTCTTTT"=>"DYS439_pool1",
"ACCAAGGCTCCATCTCAA_AATGGAATGCTCTCTTGG"=>"DYS635_pool1",
"CTCCATCCATGTTGCTCC_ACAGAGGGATCATTAAAC"=>"DYS392_pool1",
"AGCTAAACAGAGACCTAA_TAGCCCACTTGTTAAACA"=>"GATA-H4_pool1",
"CTGTTCCTCAGGCTGCAT_GTCATTCACAGATGATAT"=>"DYS437_pool1",
"AATGAAGGAAATAGAGTA_TCGAGATCACACCATTGC"=>"DYS438_pool1",
"AGTGTCAAAGAGCTTCAA_GCCGGTCTGGAAATTTAT"=>"DYS448_pool1",
"GCCTACATAGTGGAACCT_CCACACCTGGCTCCTTTC"=>"DYS481_pool1",
"TCTCTCTCTCTTTCTTTA_GGCTGTAAGTAGAGATCA"=>"DYS533_pool1",
"CAAAAAAAACAAAAACTG_GGAGGAGATGGGAGTAAT"=>"DYS576_pool1",
"CACTCTTTACAATTTTTT_ATAGGCAGAGGATAGATG"=>"DYS460_pool1",
"GTAAGCCAAACCCAAATA_GTGGCATAAGTGGTAATG"=>"DYS549_pool1",
"TGTTTAAAAAGTTCCCCC_CACCATTGCACTCTAGGT"=>"DYS449_pool1",
"GAGATTAGGAGCACAGTG_AACCTAAGCTGAAATGCA"=>"DYS570_pool1",
"TTGCTGAGGTTGAGGACA_GCGTTATCTCTGCCTTTC"=>"DYS447_pool1",
"ACATCAACATAGAATGAA_TTCAAACTCACGTTGTTC"=>"DYS444_pool1",
"GGTGACAGAGCAAGACCC_AAAAGCTATTCCCAGGTG"=>"D3S1358_pool2",
"AAGCCCTAGTGGATGATA_AGATGATAGATACATAGG"=>"vWA_pool2",
"GCTCTTCCTCTTCCCTAG_TGCCATAGACTTAAAAAC"=>"D16S539_pool2",
"CCTGTGTCTCAGTTTTCC_CTCTTCCACACACCACTG"=>"CSF1PO_pool2",
"GACTGGCACAGAACAGGC_CTCAAACGTGAGGTTGAC"=>"TPOX_pool2",
"CACACGGCCTGGCAACTT_AGCTGTCAAAAACCGTAT"=>"D8S1179_pool2",
"CCATAAATATGTGAGTCA_AGATGTTGTATTAGTCAA"=>"D21S11_pool2",
"CACTGCACTTCACTCTGA_GGACATGTTGGCTTCTCT"=>"D18S51_pool2",
"ACAAAAGGCTGTAACAAG_CACACCCAGCCATAAATA"=>"D2S441_pool2",
"TGCACCCATTACCCGAAT_TTTTTTAAAATTAGCCAG"=>"D19S433_pool2",
"GAGTGCAGGTCACAGGGA_CTAGTCAGCACCCCAACC"=>"TH01_pool2",
"TCCAAAAGTCAAATGCCC_CACTCGGTTGTAGGTATT"=>"FGA_pool2",
"CCCTGTCCTAGCCTTCTT_AAGTCCCTAAGGCTCTCT"=>"D22S1045_pool2",
"ATAGCAAGTATGTGACAA_TAGGCTGTTGAGGTAGTT"=>"D5S818_pool2",
"CTCTCTGGACTCTGACCC_GATAACAGTCTGAAAGTA"=>"D13S317_pool2",
"AGGCTGACTATGGAGTTA_GAGGTCTTAAAATCTGAG"=>"D7S820_pool2",
"TTGTCTTGTTATTAAAGG_CAAGCTTAGTACTTAACT"=>"D10S1248_pool2",
"AGTTCAAGCCTGTGTTGC_TTCCACCGCAGCACAAAA"=>"D1S1656_pool2",
"CTCCAGAGAGAAAGAATC_CATCAGTTTCCCTGGTTT"=>"D12S391_pool2",
"GTGGATTTGGAAACAGAA_CTGGCTTCTTCCCTGTCT"=>"D2S1338_pool2",
"AATAGTGTGCAAGGATGG_TTGGACTGAGATTTACAC"=>"D6S1043_pool2",
"CTGGGCGACTGAGCAAGA_TGAGGAAAATAATACTCA"=>"PentaE_pool2",
"GCCTAGGTGACAGAGCAA_ATATCTAAGAAATATTTG"=>"PentaD_pool2",
"TGGGCTCTGTAAAGAATA_ACATTTTACCGGATGGGA"=>"Ame_pool2",
"ACCTATCATCCATCCTTA_AGCATCTCTGGGCTCCAC"=>"DYS391_pool2",
"GCTCATCTTGCTCCTCAG_TGTGTTCAGTCACTGGTT"=>"DYS456_pool2",
"CCCTGCATTTTGGTACCC_AGAAAAGTCCTGAGACAG"=>"DYS390_pool2",
"TGCTAGATAAATAGATAG_TCATTATACCTACTTCTG"=>"DYS389I-II_pool2",
"TGCAGACTGAGCAACAGG_CGCCCGGCTAATTTTTGT"=>"DYS458_pool2",
"CAAGGAGTCCATCTGGGT_GACAAGCCCAAAGTTCTT"=>"DYS19_pool2",
"AGAGCTAGACACCATGCC_AAAATAATCTATCTATTC"=>"DYS385a/b_pool2",
"ATTCCTAATGTGGTCTTC_GCCAGATAACGTGTGTGG"=>"DYS393_pool2",
"GGTGATAGATATACAGAT_TTTTAGTGGAGACGGGGT"=>"DYS439_pool2",
"CCAGCCCAAATATCCATC_TGTCTCACTTCAAGCACC"=>"DYS635_pool2",
"CAAGTGTTTGTTATTTAA_TGAAAATTATGGAAGCTA"=>"DYS392_pool2",
"ATGTTATGCTGAGGAGAA_CATTTCCTCTGATGGTGA"=>"GATA-H4_pool2",
"CTGGGACTATGGGCGTGA_GCCTGAGGAACAGAGGAA"=>"DYS437_pool2",
"CTGATGCAAGAAAGATTC_GGTGGCAGACGCCTATAA"=>"DYS438_pool2",
"AGACAGAAAGGGAGATAG_TGTTGGAGACCTTTTCTT"=>"DYS448_pool2",
"AGGGGGAGAAGAAGGGGG_AGTCTCACTTTTTTGCCC"=>"DYS481_pool2",
"ATCTATCAATCTTCTACC_GCTAATATAATTAACTTG"=>"DYS533_pool2",
"TACTTTGAGAGACTGAGG_GGGAGCTAGAATTCAAGA"=>"DYS576_pool2",
"GTAAATCTGTCCAGTAGT_CAAGAATACCAGAGGAAT"=>"DYS460_pool2",
"GTAGACATAGCAATTAGG_ATCTTTCTTGCTTAATAT"=>"DYS549_pool2",
"TGTTTAAAAAGTTCCCCC_CACCATTGCACTCTAGGT"=>"DYS449_pool2",
"TGACTAGGTAGAAATCCT_TGTCCTGCACATCTTGGG"=>"DYS570_pool2",
"GGTCACAGCATGGCTTGG_TGCAAGCTCCCAATGGTG"=>"DYS447_pool2",
"CTCCACTTTAACCAGTAT_GCTTTGGTCTGGCTGTCT"=>"DYS444_pool2",
);
my @line;
my $header;
my %hash1 = ();
my %hash2 = ();
my %hash3;
my $str_name;
my $type_name;
my $num;
my @num = "";
my $str_type;
my $name;
my @type_name;
my @num1 = "";
my $num2;
die "Usage: perl $0 in > out\n" unless ( @ARGV == 1 );
open( IN, "$ARGV[0]" ) or die "Can not open file $ARGV[0]\n";
my ($sample) = ( $ARGV[0] =~ /^(.+)\.uniq.R1.fastq$/ );
print "pos\tdepth\t$sample\n";

$/="\n\@";
while (<IN>) {
    chomp;
    my @line = split( /\n/, $_ );
    my @name = split( /\t/, $line[0] );
    $name[1] =~ s/XF:i://;
    my @name1 = split( /\_/, $name[0],2);
    if($name[1]>1) {
        #print "$name1[1]\n";
        $hashty{$name1[1]}++;
        $hash1{ $name1[1]}+=$name[1];
        $hash2{ $name1[1] . '_' .$hashty{$name1[1]}  }+=$name[1];
    }
}
foreach $str_name ( sort { $a cmp $b } values %len ) {
    if ( exists $hash1{$str_name} ) {
        foreach $type_name ( keys %hash2 ) {
            $ratio = $hash2{$type_name}/$hash1{$str_name};
            #print "$str_name\t$type_name\n";
            if ( $type_name =~ $str_name and $ratio >0.005) {
                @type_name = split( /\_/, $type_name );
                $typedepth+=$hash2{$type_name};
                $num = $type_name[2] . '|' . $hash2{$type_name};
                $hash3{ $type_name[2] } = $hash2{$type_name};
                push @num, $num;
            }

            #elsif($type_name=~$str_name and $hash1{$str_name}<=10) {
            #        push @num,"NA";
            #}
        }
        shift @num;
        foreach ( sort { $hash3{$b} <=> $hash3{$a} } keys %hash3 ) {
            $num2 = $_ . '|' . $hash3{$_};
            push @num1, $num2;
        }
        shift @num1;
        $str_type = join( ";", @num1 );
        print "$str_name\t$typedepth\t$str_type\n";
        @num   = "";
        @num1  = "";
        %hash3 = ();
        $typedepth = 0;
    }
    elsif ( !exists $hash1{$str_name} ) {
        print "$str_name\t0\tNA\n";
    }
}

