#/usr/bin/perl
#use strict;

die "Usage: perl $0 fastq list > out.fa\n" unless ( @ARGV == 2 );

my %len = (
"D3S1358"=>"((TCTA){1})((TCTG){1,})((TCTA){1,})",
"vWA"=>"((TCTA){0,1})((TCTG){0,1})((TCTA){1,})((TCTG){1,})((TCTA){1,})((ATCTA){0,1})((TCCA){0,1})((TCTA){0,})",
"D16S539"=>"((GATA){4,})",
"CSF1PO"=>"((AGAT){5,})",
"TPOX"=>"((AATG){4,})",
"D8S1179"=>"((TCTA){0,2})((TCTG){0,2})((TCTA){7,})",
"D21S11"=>"((TCTA){1,})((TCTG){1,})((TCTA){1,})((TA){1})((TCTA){1,})((TCA){1})((TCTA){1,})((TCCATA){1})((TCTA){1,})",
"D18S51"=>"((AGAA){7,})",
"D2S441"=>"((TCTA){8,})",
"D19S433"=>"((AAGG){1})((AAAG){1})((AAGG){1})((TAGG){1})((AAGG){1,})",
"TH01"=>"((AATG){0,1})((AACT){0,1})((AATG){3,})((ATG){0,1})((AATG){0,})",
"FGA"=>"((TTTC){1,})((TTTTTT){1})((CT){0,1})((CTTT){1,})((T){0,1})((CTGT){0,})((CTTT){0,})((CTTC){0,})((CCTT){0,})((CTTT){0,})((CTCC){1})((TTCC){1,})",
"D22S1045"=>"((ATT){5,})((ACT){1})((ATT){2})",
"D5S818"=>"((AGAT){6,})",
"D13S317"=>"((TATC){5,})((AATC){0,1})",
"D7S820"=>"((GATA){5,})",
"D10S1248"=>"((GGAA){8,})",
"D1S1656"=>"((TAGA){4,})((TGA){0,1})((TAGA){0,})((TAGG){0,1})((TG){5})",
"D12S391"=>"((AGAT){0,})((GAT){0,1})((AGAT){4,})((AGAC){1,})((AGAT){0,1})",
"D2S1338"=>"((TGCC){1,})((TTCC){1,})((GTCC){0,})((TTCC){0,})",
"D6S1043"=>"((AGAT){9,})",
"Penta-E"=>"((AAAGA){5,})",
"Penta-D"=>"((AAAGA){4,})",
"DYS391"=>"((TCTA){6,})",
"DYS456"=>"((AGAT){12,})",
"DYS390"=>"((TCTG){4,})((TCTA){4,})((ACTA){0,1})((TCTA){0,})((TCTG){1})((TCTA){4})",
"DYS389-I/II"=>"((TCTG){4,})((TCTA){4,})(([A-Z]+))((TCTG){3})((TCTA){6,})",
"DYS458"=>"((GAAA){13,})",
"DYS19"=>"((TAGA){3})((TAGG){1})((TAGA){7,})",
"DYS385-a/b"=>"((GAAAGA){0,1})((GAAA){7,})",
"DYS393"=>"((AGAT){9,})",
"DYS439"=>"((GATA){9,})",
"DYS635"=>"((TCTA){4})((TGTA){0,})((TCTA){0,})((TGTA){0,})((TCTA){0,})((TGTA){0,})((TCTA){5,})((TCA){0,1})((TCTA){0,})",
"DYS392"=>"((TAT){6,})",
"GATA-H4"=>"((TAGA){8,})",
"DYS437"=>"((TCTA){7,})((TCTG){2})((TCTA){4})",
"DYS438"=>"((TTTTC){6,})",
"DYS448"=>"((AGAGAT){4,})(([A-Z]{42}))((AGAGAT){4,})",
"DYS481"=>"((CTT){20,})",
"DYS533"=>"((ATCT){10,})",
"DYS576"=>"((AAAG){13,})",
"DYS460"=>"((ATAG){6,})",
"DYS549"=>"((GATA){10,})",
"DYS449"=>"((TTTC){4,})(([A-Z]{50}))((TTTC){4,})",
"DYS570"=>"((TTTC){12,})",
"DYS447"=>"((TAATA){1,})((TAAAA){1})((TAATA){1,})((TAAAA){1})((TAATA){1,})",
"DYS444"=>"((ATAG){11,})",
);

my %len1=(
"D3S1358"=>"TCTATCTGTCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTA",
"vWA"=>"TCTATCTGTCTGTCTGTCTGTCTGTCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCCATCTA",
"D16S539"=>"GATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATA",
"CSF1PO"=>"AGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGAT",
"TPOX"=>"AATGAATGAATGAATGAATGAATGAATGAATG",
"D8S1179"=>"TCTATCTGTCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTA",
"D21S11"=>"TCTATCTATCTATCTATCTGTCTGTCTGTCTGTCTGTCTGTCTATCTATCTATATCTATCTATCTATCATCTATCTATCCATATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTA",
"D18S51"=>"AGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAA",
"D2S441"=>"TCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTA",
"D19S433"=>"AAGGAAAGAAGGTAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGG",
"TH01"=>"AATGAATGAATGAATGAATGAATGAATG",
"FGA"=>"TTTCTTTCTTTCTTTTTTCTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTCCTTCCTTCC",
"D22S1045"=>"ATTATTATTATTATTATTATTATTATTATTATTATTATTATTACTATTATT",
"D5S818"=>"AGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGAT",
"D13S317"=>"TATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCAATC",
"D7S820"=>"GATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATA",
"D10S1248"=>"GGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAA",
"D1S1656"=>"TAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGGTGTGTGTGTG",
"D12S391"=>"AGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGACAGACAGACAGACAGACAGACAGACAGAT",
"D2S1338"=>"TGCCTGCCTGCCTGCCTGCCTGCCTGCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCGTCCTTCCTTCC",
"D6S1043"=>"AGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGAT",
"Penta-E"=>"AAAGAAAAGAAAAGAAAAGAAAAGA",
"Penta-D"=>"AAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGAAAAGA",
"DYS391"=>"TCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTA",
"DYS456"=>"AGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGAT",
"DYS390"=>"TCTGTCTGTCTGTCTGTCTGTCTGTCTGTCTGTCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTGTCTATCTATCTATCTA",
"DYS389-I/II"=>"TCTGTCTGTCTGTCTGTCTGTCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCATTATACCTACTTCTGTATCCAACTCTCATCTGTATTATCTATGTATCTGTCTGTCTGTCTATCTATCTATCTATCTATCTATCTATCTATCTA",
"DYS458"=>"GAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAA",
"DYS19"=>"TAGATAGATAGATAGGTAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGA",
"DYS385-a/b"=>"GAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAA",
"DYS393"=>"AGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGAT",
"DYS439"=>"GATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATA",
"DYS635"=>"TCTATCTATCTATCTATGTATGTATCTATCTATGTATGTATCTATCTATGTATGTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCA",
"DYS392"=>"TATTATTATTATTATTATTATTATTATTATTATTATTAT",
"GATA-H4"=>"TAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGA",
"DYS437"=>"TCTATCTATCTATCTATCTATCTATCTATCTATCTATCTGTCTGTCTATCTATCTATCTA",
"DYS438"=>"TTTTCTTTTCTTTTCTTTTCTTTTCTTTTCTTTTCTTTTCTTTTCTTTTCTTTTCTTTTC",
"DYS448"=>"AGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATATAGAGATAGAGAGATAGAGATAGAGATAGATAGATAGAGAAAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGATAGAGAT",
"DYS481"=>"CTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTT",
"DYS533"=>"ATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCT",
"DYS576"=>"AAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAGAAAG",
"DYS460"=>"ATAGATAGATAGATAGATAGATAGATAGATAGATAGATAG",
"DYS549"=>"GATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATA",
"DYS449"=>"TTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTCTCTCTCCTCCTCTTTCTTTCCTTCTTTCTTTCTTTTCCTCTTTCCTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTC",
"DYS570"=>"TTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTCTTTC",
"DYS447"=>"TAATATAATATAATATAATATAATATAATATAATATAAAATAATATAATATAATATAATATAATATAATATAATATAATATAATATAATATAAAATAATATAATATAATATAATATAATATAATA",
"DYS444"=>"ATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAG",
);
my $fastq     = $ARGV[0];
my $list      = $ARGV[1];
my $solexatag = '';
my $seq       = '';
my $symbol    = '';
my $qual      = '';
my $i         = 0;
my @line;
my @line1;
my @line2;

my %listhash = ();

open( list, "$list" );
while (<list>) {
    chomp;
    @line = split( /\_/, $_ );
    #@line1 = split( /\_/, $line[0] );
    $listhash{ $line[0].'_'.$line[1] } = $line[0].'_'.$line[1].'_'.$line[2];
    
}
close(list);

my $strout;
open( fastq, "$fastq" );
while (<fastq>) {
    chomp;
    if ( $i == 0 ) {
        @line1 = split( /(\s+)/, $_ );
        $solexatag = $line1[0];
        $solexatag =~ s/^@//;
        @line2 = split(/\_/,$line1[0]);
        
    }
    if ( $i == 1 ) {
        $seq = $_;
    }
    if ( $i == 2 ) {
        $symbol = $_;
    }
    if ( $i == 3 ) {
        $qual = $_;
    }
    $i = $i + 1;

    if ( $i == 4 && $listhash{$solexatag} ) {
        if(exists $len{$line2[1]} and $seq =~ /$len{$line2[1]}/) {
            for(my$h=1;$h<100;$h+=2) {
                #print "$len{$line2[1]}\t$1\t${$h}\t$$h\n";
                if( ${$h}) {
                    $motif = ${$h+1};
                    $repeats = length(${$h})/length($motif);
                    $strout .= '['.$motif.']'.$repeats;
                    $strseq .= ${$h};
                }
                #else {
                #    last;
                #}
            }
            #print "$strseq\t$len1{$line2[1]}\n";
            $seq =~ s/$strseq/$len1{$line2[1]}/;
            if(length($seq) >length($qual)) {
                $qual = $qual."H"x(length($seq)-length($qual));
            }
            else {
                $qual = substr($qual,0,length($seq));
            }
            print "@"."$listhash{$solexatag}_$strout\n$seq\n$symbol\n$qual\n";
        }
        $strout = undef;
        $strseq = undef;
        $i = 0;
    }

    elsif ( $i == 4 && !$listhash{$solexatag} ) {
        $i = 0;
    }
}
close(fastq);
