#!/usr/bin/perl
#use strict;
#use warnings;
use File::Basename;
use Getopt::Long;
my %len = (
"GGTGACAGAGCAAGACCC_AAAAGCTATTCCCAGGTG"=>"D3S1358",
"AAGCCCTAGTGGATGATA_AGATGATAGATACATAGG"=>"vWA",
"GCTCTTCCTCTTCCCTAG_TGCCATAGACTTAAAAAC"=>"D16S539",
"CCTGTGTCTCAGTTTTCC_CTCTTCCACACACCACTG"=>"CSF1PO",
"GACTGGCACAGAACAGGC_CTCAAACGTGAGGTTGAC"=>"TPOX",
"CACACGGCCTGGCAACTT_AGCTGTCAAAAACCGTAT"=>"D8S1179",
"CCATAAATATGTGAGTCA_AGATGTTGTATTAGTCAA"=>"D21S11",
"CACTGCACTTCACTCTGA_GGACATGTTGGCTTCTCT"=>"D18S51",
"ACAAAAGGCTGTAACAAG_CACACCCAGCCATAAATA"=>"D2S441",
"TGCACCCATTACCCGAAT_TTTTTTAAAATTAGCCAG"=>"D19S433",
"GAGTGCAGGTCACAGGGA_CTAGTCAGCACCCCAACC"=>"TH01",
"TCCAAAAGTCAAATGCCC_CACTCGGTTGTAGGTATT"=>"FGA",
"CCCTGTCCTAGCCTTCTT_AAGTCCCTAAGGCTCTCT"=>"D22S1045",
"ATAGCAAGTATGTGACAA_TAGGCTGTTGAGGTAGTT"=>"D5S818",
"CTCTCTGGACTCTGACCC_GATAACAGTCTGAAAGTA"=>"D13S317",
"AGGCTGACTATGGAGTTA_GAGGTCTTAAAATCTGAG"=>"D7S820",
"TTGTCTTGTTATTAAAGG_CAAGCTTAGTACTTAACT"=>"D10S1248",
"AGTTCAAGCCTGTGTTGC_TTCCACCGCAGCACAAAA"=>"D1S1656",
"CTCCAGAGAGAAAGAATC_CATCAGTTTCCCTGGTTT"=>"D12S391",
"GTGGATTTGGAAACAGAA_CTGGCTTCTTCCCTGTCT"=>"D2S1338",
"AATAGTGTGCAAGGATGG_TTGGACTGAGATTTACAC"=>"D6S1043",
"CTGGGCGACTGAGCAAGA_TGAGGAAAATAATACTCA"=>"Penta-E",
"GCCTAGGTGACAGAGCAA_ATATCTAAGAAATATTTG"=>"Penta-D",
"TGGGCTCTGTAAAGAATA_ACATTTTACCGGATGGGA"=>"Ame",
"ACCTATCATCCATCCTTA_AGCATCTCTGGGCTCCAC"=>"DYS391",
"GCTCATCTTGCTCCTCAG_TGTGTTCAGTCACTGGTT"=>"DYS456",
"CCCTGCATTTTGGTACCC_AGAAAAGTCCTGAGACAG"=>"DYS390",
"TGCTAGATAAATAGATAG_TCATTATACCTACTTCTG"=>"DYS389-I/II",
"TGCAGACTGAGCAACAGG_CGCCCGGCTAATTTTTGT"=>"DYS458",
"CAAGGAGTCCATCTGGGT_GACAAGCCCAAAGTTCTT"=>"DYS19",
"AGAGCTAGACACCATGCC_AAAATAATCTATCTATTC"=>"DYS385-a/b",
"ATTCCTAATGTGGTCTTC_GCCAGATAACGTGTGTGG"=>"DYS393",
"GGTGATAGATATACAGAT_TTTTAGTGGAGACGGGGT"=>"DYS439",
"CCAGCCCAAATATCCATC_TGTCTCACTTCAAGCACC"=>"DYS635",
"CAAGTGTTTGTTATTTAA_TGAAAATTATGGAAGCTA"=>"DYS392",
"ATGTTATGCTGAGGAGAA_CATTTCCTCTGATGGTGA"=>"GATA-H4",
"CTGGGACTATGGGCGTGA_GCCTGAGGAACAGAGGAA"=>"DYS437",
"CTGATGCAAGAAAGATTC_GGTGGCAGACGCCTATAA"=>"DYS438",
"AGACAGAAAGGGAGATAG_TGTTGGAGACCTTTTCTT"=>"DYS448",
"AGGGGGAGAAGAAGGGGG_AGTCTCACTTTTTTGCCC"=>"DYS481",
"ATCTATCAATCTTCTACC_GCTAATATAATTAACTTG"=>"DYS533",
"TACTTTGAGAGACTGAGG_GGGAGCTAGAATTCAAGA"=>"DYS576",
"GTAAATCTGTCCAGTAGT_CAAGAATACCAGAGGAAT"=>"DYS460",
"GTAGACATAGCAATTAGG_ATCTTTCTTGCTTAATAT"=>"DYS549",
"TGTTTAAAAAGTTCCCCC_CACCATTGCACTCTAGGT"=>"DYS449",
"TGACTAGGTAGAAATCCT_TGTCCTGCACATCTTGGG"=>"DYS570",
"GGTCACAGCATGGCTTGG_TGCAAGCTCCCAATGGTG"=>"DYS447",
"CTCCACTTTAACCAGTAT_GCTTTGGTCTGGCTGTCT"=>"DYS444",
);
my @line;
my $header;
my %hash1 = ();
my %hash2 = ();
my %hash3;
my $str_name;
my $type_name;
my $num;
my @num = "";
my $str_type;
my $name;
my @type_name;
my @num1 = "";
my $num2;
die "Usage: perl $0 in > out\n" unless ( @ARGV == 1 );
open( IN, "$ARGV[0]" ) or die "Can not open file $ARGV[0]\n";
my ($sample) = ( $ARGV[0] =~ /^(.+)\.need.fasta.misa$/ );
#print "pos\t$sample\n";

while (<IN>) {
    chomp;
    my @line = split( /\t/, $_ );
    my @name = split( /\_/, $line[0] );
    if($name[2]>1) {
    
        $statLoci{ $name[1] }+=$name[2];
        #$hash2{ $name[0] . '_' . $line[3] } =$name[2];
    }
}

open( IN, "$ARGV[0]" ) or die "Can not open file $ARGV[0]\n";
while (<IN>) {
    chomp;
    my @line = split( /\t/, $_ );
    my @name = split( /\_/, $line[0] );
    if($name[2]>1 and $name[2]/$statLoci{ $name[1] } > 0.02) {
        $outName = $line[0].'_'.$line[3];
        print "$outName\n";
    }
}
        

