#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;
use Getopt::Long;
my %len_0 = (
    "CAAGATCATGCCGCTGCC_TAAGTAGATG"=> "D1S1646",
    "CCTCTTTGTTGCAGTGAT_TTTTCTCAAA"=> "D1GATA113",
    "GATGGATGGATGGACAGA_GCTCTTCTTT"=> "D1S552",
    "GAGGTGAACCAAGGGACC_AGAAGGACTG"=> "D1S1598",
    "CCAAGTGACTGAGGGTTG_GATGGCTGGG"=> "D1S2134",
    "GCTTCCGTAACTACATGA_CATGTATTAG"=> "D1S3734",
    "GTTTCCTATGTTCCAAGC_CAATTTAGTT"=> "D1S1162",
    "TGTCTTTATCAGTAGTGT_GCCATGGCCC"=> "D1S3733",
    "TGTTGAGGTAACTTTTTG_GGGCAATTAG"=> "D1GATA133A08",
    "GATTTGGGCAGCAACTTC_TTTCTTTTGC"=> "D1S1600",
    "CATGGTACTCAGCAGGGC_AGTACTGCTT"=> "D1S1679",
    "GTATAGCTACAGTTTTTC_TTGTATTTCT"=> "D1S1677",
    "ACATATATTTGTGGATGG_TGTGGGCAAC"=> "D1S518",
    "TGTGTTGTTATATTCTGG_GGCAGGGGGT"=> "D1S1667",
    "AATCACTAGGGAACCAAA_GCCTGTGTTG"=> "D1S1656",
    "GAGCTGTGATCACGCTAC_TTCAGCCTCC"=> "D1S1171",
    "GTGTTTCAGGGCTGTGAT_CCTTCTGTCC"=> "D2TPOX",
    "GCCTATTGTGGGATCTTG_TCTGCTCTTG"=> "D2S2952",
    "TCTAAATGGCATATACAA_GGACTTCTCA"=> "D2S1360",
    "GGCAGAAGCGTGGCAGTT_ACACAGCCAA"=> "D2S405",
    "GGCTGTAACAAGGGCTAC_GGAGCTAAGT"=> "D2S441",
    "GGTTGATATATTTATCCC_GGCTAGTGAT"=> "D2S2970",
    "AATATCTACTAAGTACCT_AAACCTACAT"=> "D2S1379",
    "TTACCTGTGAGTATGTGT_AGCTACTGAG"=> "D2S1776",
    "CTCCAATGGGTAAGCTCC_AGAGTGAGAC"=> "D2S426",
    "GGATTGCAGGAGGGAAGG_GGATTTGGAA"=> "D2S1338",
    "GCTGTGCCACAGTTGAGT_TTCCTGTTCA"=> "D2S424",
    "TGTATTTGGAAGCATTTG_TTGCTACTTC"=> "D2S1363",
    "CTATGTGTACAGAGATAT_AGACATTATA"=> "D2S427",
    "CAGGCAGGTAGATAGACA_ACACTACACA"=> "D3S2432",
    "AGAAGAATGTGTTTGGTA_TGCACTGTTT"=> "D3S1768",
    "CTCATGAAATCAACAGAG_TATGATTCCC"=> "D3S1358",
    "AAAGTGTATTAGATTAGT_CTTGGCTCCC"=> "D3S2452",
    "GCTGATCCTGTGGTTTGT_AACCTATGTC"=> "D3S2388",
    "CCTCCAGGGAGACAAAAT_ACTTGCCAGA"=> "D3S4529",
    "TTCTTAACTACAGAAGCA_CCAGTTATGA"=> "D3S3045",
    "GTCTGGCCCCATCTCTCT_CGGAAGGAAG"=> "D3S1744",
    "AAGAGAGGGCTGAACTCA_TGAGGTCTTT"=> "D3S3053",
    "CCAGACTTCCACAATCAC_AAGAGAAACA"=> "D3S3041",
    "CCTGACATTCCTAGGGTG_AGCAAAACAA"=> "D4S2366",
    "AATTCAGCAAGTTAAGAA_TCAATTCATC"=> "D4S2408",
    "GAACAGGAATAAGTTGCA_GGCTGTAACC"=> "D4S2632",
    "GCTTCATGTGTGAAGTGC_GCTGTGGGAA"=> "D4S3251",
    "TCTGGGCAAACTCATTTC_TGATGCATGT"=> "D4S2404",
    "AGAATTGTTGTCTGTAGG_GATGTGGGAA"=> "D4S2364",
    "CCAAAAGTATCTGGCATG_ACTCATGGTA"=> "D4S1628",
    "AATTTCAGGACTAGGGCA_CCCAAAGCTA"=> "D4S2634",
    "TGGGTAGGTAGGTAAAGA_AATTGTGTGA"=> "D4S3250",
    "ATGAGGGTCTGTTGGTAG_TGGTCCCTAG"=> "D4S1644",
    "TTGCCAGCAAAAAAGAAA_AAAATTAGGC"=> "D4FGA",
    "GTTGGTTCTGCTTTTTCT_AACAGACAAA"=> "D4S1629",
    "GTGACACCATAGGGTAAC_GAGGGTGTAC"=> "D4S2368",
    "CCAAAAGCCTTGATTACA_AGCTGCTTCC"=> "D5S2845",
    "AATCAAATCAAAAGGACA_TTTTAGGTTC"=> "D5S2856",
    "GGGCAACACAGACTCTGT_CCATCTTATT"=> "D5S2500",
    "ATACCATTCATAAAGCCT_GTGCCTAGCC"=> "D5S1474",
    "TGAATCAATTACCCTAAC_CTAAGGCTTC"=> "D5S2499",
    "CATAGCCACAGTTTACAA_GGTGATTTTC"=> "D5S818",
    "TTTCCTGTGTCAGACCCT_AATGAAGATA"=> "D5CSF1PO",
    "AATTGCATAAGCCAACTC_GCTTTAATAA"=> "D5S820",
    "TGTTTGTGGCAGAGTGTG_GAAAGCACCA"=> "D5S1471",
    "GGGCTGATGAGGTGAAAT_CTGGGGGATA"=> "D6S477",
    "TGGCAAAACCCCATTTCA_GCCACCTTTG"=> "D6S2439",
    "ATGGATGGGTGGATGCAT_CATCCACCCA"=> "D6S1017",
    "TCACAGGTTGCTAGACAT_GTAGAGATAA"=> "D6S1960",
    "TGAGTACATTCTAGGCAC_CCAACCTCAC"=> "D6S1275",
    "AGCATCACAAGTTAAGTG_ACCTGCAAAG"=> "D6S1052",
    "CATATTGTGAAATTTCTC_GGATGGGTGG"=> "D6S1043",
    "AAAGCCTATTTAGTCAGG_GCCAATTCCT"=> "D6S474",
    "GCAGATTATATCTATCCT_GGAATGAGGA"=> "D6S2409",
    "GGACTTTTCAGCCTTCAT_GGGTTGTATT"=> "D6S2436",
    "TTCACAATGAAACTCATT_CAAAAATCTG"=> "D7S3048",
    "TCATAACCATGTAAGCCA_CAATAATGCC"=> "D7S1821",
    "TCCTGGTCCAGGACAAAT_TCTTTATGGC"=> "D7S817",
    "TCTATCTATCTTTTTATA_ACCCAGGATT"=> "D7S1818",
    "TGGTACTTCTCAGCTTCT_TCTTTTCTGT"=> "D7S3069",
    "AATGTTTACTATAGACTA_AAAGGGTATG"=> "D7S820",
    "TGTATCAGTCTCAGGATA_TCACACTCTA"=> "D7S1820",
    "CCCACAGAGGCAGAACTA_TCAGCCTTCA"=> "D7S1799",
    "CTTTGATCAATGCCTCCC_TGTTGATAAA"=> "D7S3052",
    "CAAGGATATCTCTTCTCA_CCATTTCTTC"=> "D7S3070",
    "ACAATCCAGTAATCTATA_ACAGGCACAT"=> "D8S1145",
    "CCCACATGTGAATTTCTT_CCTCTAATGT"=> "D8S1477",
    "TCAGCTATGAGAAAAGTT_TTGACCCTTG"=> "D8S1104",
    "AAGTATAATATCCTTTTT_GCAAAGCAGT"=> "D8S2332",
    "GCAATATCAAACCTGGTG_CAAGGACGCC"=> "D8S1105",
    "CACTGTGTGTGTCTTCTC_TCTCCAGTGT"=> "D8GAAT1A4",
    "AGTGGCTTAATGTATTTG_ATCTCTCTCT"=> "D8S1132",
    "AGATGATGTTGTTGTTGA_TCCTGTTGGC"=> "D8S592",
    "CACGGCCTGGCAACTTAT_ATTTACCTAT"=> "D8S1179",
    "TGTGTCATTATATGCACA_GTCAAGCTTT"=> "D9S2156",
    "GCTCCTGTGCCCTTTTGA_GAGAATCTTG"=> "D9S921",
    "TGCTGGGCTTAGAAATAT_CCTATGTTTT"=> "D9S1121",
    "AAATACAAAAATCACTGG_TGTAAGTTCT"=> "D9S2154",
    "TTACTAGATGTATTAGCC_CAGCCAAAAT"=> "D9S319",
    "ACAGTTTTAAGTAAGGAT_TCTCTCTCTT"=> "D9S1118",
    "CTACACCCGGACTCCAGT_TGCCCACACA"=> "D9S304",
    "CACCTGTCTATCCATTCG_CAAGATGGTG"=> "D9S2148",
    "GCTTATTTGTGGGGGTAT_GCACCCAAAG"=> "D9S1122",
    "GTGGTTGAAACACTGAAA_TAAGGCACAC"=> "D9S2128",
    "CTTCTAAAAAGGAAATAA_TCTCCCCATA"=> "D9S2145",
    "TGCTGTGTTTGTTATAAT_CACCTTGGGT"=> "D10S1435",
    "CCTCGTTGGAGTGGACCA_CAAGTCATTC"=> "D10S1430",
    "AGAGCCTTAAACATATAG_CCTGAGCAAC"=> "D10S2474",
    "TGGCCGATCCTGAAGCAA_GTCATCCTCT"=> "D10S1426",
    "CACCCAAAGTTAACCATG_TCACATGTAC"=> "D10S1428",
    "CCAACTTTTGAGTATGGA_CACAATCCAA"=> "D10S1432",
    "CACCAAATTGGCATTCCT_TTCTTAAGAC"=> "D10S1246",
    "CACTGTTTTAATTGCTGT_GGAGTTGCGT"=> "D10S1425",
    "CCAATCTGGTCACAAACA_GTCTTGTTAT"=> "D10S1248",
    "GCTTCCGAGTGCAGGTCA_GGCAAAATTC"=> "D11TH01",
    "GGAACTGGAGTAAACAAG_ACATGGCAGC"=> "D11S1999",
    "CAGATTTCTGCTTTCCCA_CCAGAAAGGG"=> "D11S1981",
    "ACAATGAGGTGCAAGAAT_ATGGATGGAT"=> "D11S2368",
    "GTGTCCTACAAATAGAAA_CACATATGAT"=> "D11S2364",
    "AGAAGGCCTTGAGACATC_TGCCAACTTC"=> "D11S1392",
    "TGCAGATGCTCTGTTCTT_GCAGTATGAC"=> "D11S1393",
    "CCCAGGCTCAAGCCATAA_CCAATTCTTA"=> "D11S2363",
    "CACACCAGCCAGTTATTA_GGACATGGCC"=> "D11S4960",
    "TGAAAAACATCTGTTGAG_AAGCATTGTG"=> "D11S1367",
    "ACCCAGCAAAAACAACTG_CTGTGTCAAA"=> "D11S4951",
    "CCAGGTAATATTTACCCT_GGTGCCTTGC"=> "D11S1998",
    "AATACGCAATTCTGGATT_CCATCAGATA"=> "D11S4463",
    "CCATCAAGAGAGGAATGG_TGCTGTGAAT"=> "D12S374",
    "AGAGATAGGACAGATGAT_AAGAATAATC"=> "D12vWA",
    "TCCAGAGAGAAAGAATCA_CTCCATATCA"=> "D12S391",
    "TCCATACCCATGAGCCAA_AGAGAGACAG"=> "D12S1057",
    "TGGGTAGGGCAAGGTATC_GCATAAGAGA"=> "D12S2080",
    "CATAATATTGGACAGTAA_CGTATATTAG"=> "D12S1301",
    "GGTGTGATTAGCATGAGC_TCAAATTCAA"=> "D12S1056",
    "TTTGCTTTGATTCCTAAA_AATAAGCATT"=> "D12S375",
    "TGTTGCTTCCAAGATTAG_GTGTGATAGA"=> "D12S1297",
    "TCCTGCTTCAAGCCCTGA_TTGCTACCCT"=> "D12S1064",
    "CTCTGTCATCTGTCTGTC_TAAATGCTAC"=> "D12S1030",
    "GGAATAATCATTGTAGAT_GCAGCTTCGA"=> "D12S1023",
    "GGACTTTCTAGCCTATTG_CAATCTCTAT"=> "D13S1493",
    "AGAATCCTTCCAGCTAAT_CAGCTTAAGT"=> "D13S325",
    "ACACACCTATATACCTTC_CAAAGGTTTA"=> "D13S1492",
    "TGTTAAACTATCATCTGT_CACCTTCTTT"=> "D13S801",
    "ACCTATCGCTATGCCTGT_TCAATTAGGC"=> "D13S1824",
    "TGCCCTACCTCCTGTAAT_GTTTCCTCTT"=> "D13S792",
    "GACTCTGACCCATCTAAC_GCCATAGGCA"=> "D13S317",
    "CAGCCCAGAGATGCTGAA_TGACATTCAT"=> "D13S790",
    "ACATGAACTATGATTCAT_TCAAGTCATG"=> "D13S793",
    "TGTTTGGTAGCTTAATTA_TCACAGATAT"=> "D13S796",
    "CCAGAGAAGCAGAACTAA_ACACGTATAT"=> "D14S742",
    "TGCCTTTTCTTTTCTGGA_AGAAAGGTCT"=> "D14S1280",
    "TGGTACAGGTAGATAAAT_CCATTATATA"=> "D14S608",
    "TGTACCTGTCACTGGTCT_GGAGCTTATA"=> "D14S741",
    "AGTAAATCTCTAGATAGA_AGAGCTTTAG"=> "D14S1432",
    "CATTCACCAAATTATATT_CACACTTTAT"=> "D14S748",
    "CACATGAGGCAATTCCCA_GCCTTCTGTG"=> "D14S747",
    "TGGCGTGTTCCACTCTTT_AGTGGGAAAG"=> "D14S125",
    "TGCTTGGGTTCGAATGCA_GGATTGCTGC"=> "D14S588",
    "TGGTTGGTTGTTACACAG_TCATGGAAAA"=> "D14S126",
    "AGTGAGCCAATTCCTTGT_TCCGGAGCAG"=> "D14S1434",
    "GCCTGGGCGACAGTAATG_CCAGAGAGAC"=> "D14S1426",
    "TTATCGAGAGCAATGGAA_GGTCAGCCTC"=> "D15S817",
    "CCAGCAGCTTAGATTGAT_GCCAAATGAT"=> "D15S1513",
    "ACCTATTACTCTCTATTT_TTTTTTCAAA"=> "D15S822",
    "TCCTACCTTTGTTACTCT_GCATTCCCTA"=> "D15S1232",
    "CGTCTTCCCAACATAACA_TTTATGTGTG"=> "D15S659",
    "TGTTGGATGGGAATTGAT_CACAGCTGAG"=> "D15GATA153F11",
    "AAGATCACATCTGTTGGC_ACATGCACAC"=> "D15S1507",
    "TGAATTGGAAATATACGT_TGCGTCACTG"=> "D15S1514",
    "CCATCAGCTCCTCCAAAC_TGCTTGAAAA"=> "D15S642",
    "CCATTCCATTTCCTAACT_ATTTCACTCT"=> "D16S2622",
    "AAGGGTAATTGGACTCTG_CCTATCTCTA"=> "D16S2619",
    "GCTCAGAGATTCTCAGAA_TTCCTCTTAG"=> "D16S769",
    "TGTGTTCAAGCATGGGTG_TTACAATAGC"=> "D16S3253",
    "GGGGAGATCCTGCCTCTA_GGAGTGCCTG"=> "D16S3393",
    "GAGGATTGGAGGAGGGTG_CAACCCTGTC"=> "D16S752",
    "GAGGCAATTTGTTACAGA_TGAAAAGTAA"=> "D16S2624",
    "GGGGACACATGAGACCCT_TCAGATCATT"=> "D16S2625",
    "CTGCCCTGCATTACAATT_CCAGTCTTCC"=> "D17GATA158H04",
    "ACCCTGTCTCAGATAGAT_TAAGGTGAGG"=> "D17S974",
    "CAACCATCAGTGATTTGA_TCTTAATCCT"=> "D17AC001348A",
    "ACCTACTTAACCTTATTC_CCAGTCCATG"=> "D17S2196",
    "AGTGAGACCCTATCAAGA_ATTTTCTTTC"=> "D17S1294",
    "AAGTCGGTGCATTATGGG_CCTATACTTT"=> "D17S1299",
    "CAACAGAGCAAGACTGTC_TCTCCCTGTG"=> "D17S1290",
    "GTATTCTCTGCCCAATTT_GATACATGCT"=> "D17S2182",
    "TCTTGACAGGGAGGTGGT_CCTGGCCAGA"=> "D17S1535",
    "TGCCATGTAAAAATACAT_TGAAGGTAAA"=> "D17S1301",
    "ACTCCCTGATTTTTAGCT_TCCCCTAATA"=> "D18S976",
    "AGATACTCATTTATACCC_TGTGTGTTTA"=> "D18S869",
    "TGTGTGAGCCAGTCCTTC_CTGGTGTTAG"=> "D18S536",
    "GACAAAAGCCACACCCAT_CAGAAATATA"=> "D18S535",
    "GTGGATCTTGAGATTTCT_GGTTCTCCAG"=> "D18S972",
    "TCTTGTGAGCCAATCCTT_AACAGAACCA"=> "D18S548",
    "ACTCTGAGTGACAAATTG_CTATTTCTTT"=> "D18S51",
    "GGTTCATCCAAACATGGT_CCACACAACA"=> "D18S1367",
    "CCAACAGACAAAGGTTAC_CCTAACCAAA"=> "D18S1358",
    "AGGGATTTCTACAGACAG_GAGCCAATTC"=> "D18S870",
    "AGGGAGAATCACTCTTCA_CAACCTGGGC"=> "D19S1165",
    "CCTAACTCAGGCGGCCAA_GGTGACAGAG"=> "D19S1036",
    "CATCATCTATCAAGGTGA_AAAAAGATAA"=> "D19S719",
    "GCTCTAGGAAGGCAGGGT_TGCCTCTATA"=> "D19S400",
    "CACAAGAATCTGTATTAG_CTCACCTTCC"=> "D20S604",
    "TTAAGTGATTTGTCCACC_CTTCCAACTG"=> "D20S161",
    "CAATTATTAACGTTTTGC_GGGTTCAGAA"=> "D20S1145",
    "ATTTCTGGGCTGGCGGGG_CCATCCTAGC"=> "D20S607",
    "TGAGGAAAAAGCTCTCTG_AAGAGAGGAA"=> "D20S481",
    "AAATAAAACAATAAACTC_CAGACCACAC"=> "D20S480",
    "TGTGTATTTCTCTCTCTC_CCACTCCATG"=> "D20S469",
    "CCTCACATTTTGGAATTC_GATGACTGGA"=> "D20S430",
    "GGAAGCGTGTACTAGAGT_CCTCCATATC"=> "D20S482",
    "TGTAGACAGCCTATTGTG_TTCTTAGAGG"=> "D21S1432",
    "CATGTACATGTGTCTGGG_GTATTCTCAT"=> "D21S1437",
    "TCAAAGGTCTATACAAGC_GTAACACTAA"=> "D21S1409",
    "CATTCCCCTCTCCAATTG_TGAGTCCTGT"=> "D21S1435",
    "CCAGTGCACAGACTGTAC_TAAGACTTCT"=> "D21S1442",
    "GAAACCACTCTAAGACAT_CTTCCCTTGT"=> "D21S226",
    "AAGATGGCATGAGTATGT_CGTTGCAGGG"=> "D21S1413",
    "AGCAAGACACCATCTCAA_TGAGAAATTT"=> "D21PentaD",
    "TTTATGTATTTACTATAC_ACTGGTAACT"=> "D21S1446",
    "GGAGCCAATTCACCTAAT_CAGAACCTAT"=> "D22-GATA198B05",
    "AAAAATAATTGAAGTAAG_GTATCGCTGG"=> "D22S686",
    "TGATTGCCTGGATGACTG_GTGACAGAGC"=> "D22S533",
    "AAGACCAAACATAGTAAG_CAATTAACCA"=> "D22S691",
    "CAGGACAGTTCATGGAGC_TGTATCACTT"=> "D22S1265",
    "CATGCGGTGGACTAGCCA_GGCAATAGAG"=> "D22S692",
    "TCCTAGCCTTCTTATAGC_GCGAATGTAT"=> "D22S1045",
    "TGAGAGATGGAGTTTGCC_TGGTACCATT"=> "D22S534",
    "GCTTGAAGAAGGAGCTCA_CCTGGCTGAG"=> "D22S444",
    "AGACTTTATCATAAGTAA_GTAAAAATAC"=> "DXS6807",
    "TTCTGTCGGCTGAAATTA_AATACACATT"=> "DXS9902",
    "CACCATACCCAGCCCTGA_TGAAAGCCAC"=> "DXS6810",
    "GGTGCCAAACTCTATTAG_TGAGCCCATT"=> "DXS7132",
    "AGTGTTTTTCCAAGTTAT_ACCTAGACTA"=> "DXS10075",
    "CTCAAAACAAAAAGGAAC_ATATTCACCT"=> "DXS6803",
    "CGAGCACACCTACAAAAG_GCATCCAGAT"=> "DXS9898",
    "CCTAGAGGGACAGAACCA_CATGTAAGTT"=> "DXS6789",
    "AGGTGTAGCTTCCTTAGA_CATCTTCCAA"=> "DXS7133",
    "CTTCTGCAAGCCATTTGG_ACCTCAGTTC"=> "DXS7130",
    "TGAATAATCTATGTATCA_AAAAGTTGAC"=> "DXGATA165B12",
    "CATCTCTGTCTCCATCTT_CCCCTGTCTA"=> "DXHPRTB",
    "GTGCCCAAAAGATATTTG_CCCTTTATCA"=> "DXS7423",
    "TTATTTGTCATTCCTAAT_AAAAATGAGG"=> "DYS393",
    "GGTAGAAATCCTGGCTGT_AACCTAAGCT"=> "DYS570",
    "CTCAGCCAAGCAACATAG_GGGAGTAATA"=> "DYS576",
    "AATGGATAGACATAGGTG_AGTGAGAGCC"=> "DYS522",
    "CTATAAGTTATCTTTAGC_GCTCAAGGCA"=> "DYS443",
    "TTCAATCATACACCCATA_GGTTGCAAGC"=> "DYS391",
    "GCACATACATTGTTTATA_CTCACTTCAA"=> "DYS635",
    "AGATACATAGGTGGAGAC_ATGCCTGGCT"=> "DYS439",
    "CTCTCCAGCCTGGTGATA_GGCTTTCTTG"=> "DYS641",
    "CAGGTGTTCACTGCAAGC_CCCCCAAAAT"=> "DYS643",
    "TGTCCGTCCATCTCTATC_TGGATGAAGG"=> "DYS513",
    "TCTATCAATCTTCTACCT_TGATCAGTTC"=> "DYS533",
    "TGCTGTGTCACTATATTT_ATGGATAGAC"=> "DYS461",
    "TCCATATCATCTATCCTC_TAGCAAGCAC"=> "DYS460",
    "GAAAGCCCCATTCCCTAG_TGGGTAACAG"=> "DYS445",
    "TGTGGTGATGATTTCATA_CCAGCCCTTA"=> "D1S1597",
    "TTCTGCTGTACACGTATG_AACCTGGCCT"=> "D1S3669",
    "TGAGGAAGAAAGGAGGAA_TTTGCCTTGG"=> "D1S1676",
    "CGGTGACAGGTAGGTAAG_GTCAGTTGGC"=> "D1S3467",
    "TGTGCTCATTTTTAACTG_TGCCAGAGAA"=> "D1S551",
    "TCGAGTCAGCAGTGTGAC_CTCTAACCCA"=> "D1S1588",
    "CACATACCAATGGCGGAG_TGCCAATTAT"=> "D1S1631",
    "ACATAGCAGGCACTAGCT_CCCAAAACCC"=> "D1S534",
    "ACACTCCCACCTGGATGA_CTATGGAGGT"=> "D1S1653",
    "CCTTCCATAGCTGATACT_GCAACAGAGT"=> "D1S1165",
    "TCTTTTTCTGGCTTCATG_TTCAACACTA"=> "D1S1589",
    "TGTGGGACTTGGCATCCA_GTTAGAGTGC"=> "D1S2141",
    "GTTTGTGTGTGTAAAACA_CCAGCAATGG"=> "D1S549",
    "TCTAGAGAGAGAGAACCA_TCCCTAATAA"=> "D1S1644",
    "TGCCTGGAAAAACACAAG_CCATCAATGG"=> "D1S517",
    "GTGACTAAGTTAGCACAC_CTCGAAATCC"=> "D1S1609",
    "GGAAATTGATAATGATAG_TTATCCTTAG"=> "D2S1394",
    "TTGTATCTCTTTCCATGG_GCCAAAGCAG"=> "D2S1387",
    "AAAAATTAGTCGAGCATA_CCCAGATCAT"=> "D2S274",
    "AGAATGGGAGCAACATGA_AATCAGGCTG"=> "D2S436",
    "GTTATGTAGAAGAGTCAG_TTAGTTTTAC"=> "D2S410",
    "GGATTCATGCAGTTCAAA_ACGGATGCAG"=> "D2S437",
    "AACTACATTGGTCCAGGT_GGTCAGTTGC"=> "D2S1399",
    "AGTAGAAGCCAGGGACAT_AACCCTGGCA"=> "D2S1353",
    "CCAACTTCCTACTTGGTG_TGTTCCCAGA"=> "D2S434",
    "GGATGTACAAATGGGTAG_GCTGGGTCCT"=> "D2S2968",
    "TCAAGTGCAGCCTGACTT_GCTCAATGAT"=> "D3S3050",
    "CAGAACATTCTGCTCGCA_TGTTTAAAGT"=> "D3S2431",
    "TTTTCAACTGGCTTTGAC_CCCTGCCTAC"=> "D3S4547",
    "CTTCTCAGCCTCCATGAC_AAATTAGTAA"=> "D3S1766",
    "CCAAATTGTGTAAGTTCA_TCTCTCTCTT"=> "D3S2454",
    "GGGAAACATATTATGTCT_AAACTGGTTT"=> "D3S2459",
    "ATAGCATTGCTTCCCCTT_AGTGAGTACA"=> "D3S2460",
    "AACAAATTCTTAATTGGA_CTCAGAGTCC"=> "D3S1764",
    "TCAAAACCAGGAGTAAAA_TCAATCTAAT"=> "D3S1763",
    "ACAAACTTGTACATTCTG_TTCAGGACTG"=> "D3S2418",
    "GAAACACTTTTCATTCCT_GGCATGGCAT"=> "D4S2397",
    "CCCTCCTGAAAAACACAA_CAGACAAAGG"=> "D4S1627",
    "GAGTTGAGAAGAAAGGAA_GCAAGTAAAT"=> "D4S3254",
    "CAATGTCATAGAAGAGAT_TGAAAAAATG"=> "D4S3248",
    "CCAACACCCCTGCTACTT_TTAAGCAAAG"=> "D4S1647",
    "AGTCCTGAAGACATCTTG_GATTAGGAGA"=> "D4S2417",
    "TGTATTTTTATAAGGAGG_TGGTTTTCAT"=> "D4S2390",
    "ACTCCTATATCATTGTTT_CAGGCTCAGA"=> "D5S2488",
    "TTTCCTGAGGTTTCTACT_CAAATGTGCG"=> "D5S807",
    "AGCACAGCTCATCTTCCC_AGAGAAGGGC"=> "D5S1486",
    "TCTCTTCATGTCTCTCTC_ACTATATTCC"=> "D5S1470",
    "TGGGTAAATATCTTATTC_TCAAAGTGTT"=> "D5S2507",
    "TGCATCCTTCTCTGATTA_AGTAAAAAGA"=> "D5S806",
    "TGGTTCCTGTAATATGAT_AGAATAAATG"=> "D5S1459",
    "TCATAATCTGGGGGAAGT_GGTAGCTCTT"=> "D5S2501",
    "TTATCTGACACTTTTCCT_GAATTCAGCA"=> "D5S1484",
    "GGACCAAATAAATGAATA_AAGAGCTATT"=> "D5S816",
    "GGTCCCTGCCTACTGATT_TGGCTGTGAT"=> "D5S1480",
    "TTGTAGGTCAAGGAGCAT_TCATTTAAAT"=> "D5S1456",
    "AGGGATTCCAGGCCAAAT_TTCTGACAAA"=> "D6S1279",
    "TCTTTTGCTGGCTCTGCA_CATTAGAAGC"=> "D6S1266",
    "CACTTAGAGTATTCCAGC_AACAAAGCGA"=> "D6S1281",
    "GGGACCTTGTGATCATGT_AGTCAGGTTT"=> "D6S1053",
    "GCCTCATTTTATCTACCT_TGCCATCAAT"=> "D6S1031",
    "GGACCTATAAATAGCTTG_AGTTTCTAAG"=> "D6S1021",
    "TGGAAAAATACATAAATA_TCCAGTATGG"=> "D6S1040",
    "CATCTTGTTGGCATAAAA_AACAGAGTGA"=> "D6S1009",
    "TCTGTGTCAACTGTTATC_TGTTCAAGGG"=> "D6G15833",
    "GAAAACTCAAGCTCAGAA_CTTGAATCCA"=> "D6S1035",
    "TCACAGAACTTACAAGTG_TTAACCCTGC"=> "D6S1277",
    "TCTGTATATGGACATAAC_GAGTTCCATC"=> "D7S3051",
    "TCCAGGTGGCTGAGAGAC_AACTGTTGCC"=> "D7S3053",
    "AGCTTTAACAGATGTCAG_CCTCCTCAAC"=> "D7S1813",
    "TCCCAAAACCACTTAAGT_TGCAATTACT"=> "D7S1817",
    "AGTCCTGACCTAACCTTC_CTGTGTGACT"=> "D7S1824",
    "AGCCAGAGTAACCCTTTA_GCAGATCCTC"=> "D7S1823",
    "GCAGGTTTTCCAAAGGGA_GATTAAAGAA"=> "D8S1458",
    "TTCCACCAGCAGTGTGTA_TGTGCCCATC"=> "D8S1116",
    "GATATCTCTCTCTCTTCT_TGCTTCCTTT"=> "D8S593",
    "TGTCACAGTGGTTTATTT_TCTGCCAATG"=> "D8S2324",
    "CAAGGAGAAATGGAATGC_CCAGCCCAGA"=> "D8S1119",
    "TTATTGTTATCAATCTCT_CACAGATAGT"=> "D8S1471",
    "CCAGGCTACATTTCCAAA_TAGAGCCTAC"=> "D8S1128",
    "GGCAGCTATTTTTGTAGG_TCCTCTTGGG"=> "D8S1100",
    "GGACCACTGCCTAAGGAA_CCAAGAAGGT"=> "D9S922",
    "CCAAAATCAGGATTTGGA_CTCCAGTGCT"=> "D9S253",
    "CAAAAATTAGCGTGTGTG_GCTACTGCTG"=> "D9S2157",
    "ACTAGTGTTATGACACTT_TGTGTTATGT"=> "D10S2481",
    "TTAAATCAAGGTCTTTCA_CGGTAAGAGA"=> "D10S1208",
    "CCCTGCATCCACCTTTGC_AATAGAGGCA"=> "D10S1221",
    "CCTTAACTGGCGACATCA_AAGGTTACTG"=> "D10S1427",
    "TGACAGAGTGAGACCCTG_ACTTGATAGC"=> "D10S1239",
    "CAGAGACTCTGCTAAGCA_CAGTATTGTT"=> "D10S1230",
    "GGACACAGGTCCCTGGGA_GGTTGGATGA"=> "D10S2322",
    "TCAGAATGGACTATAGGA_CTAGTATCCA"=> "D11S2362",
    "CACCAGTAAGAAATGAAT_CCAATTGACA"=> "D11S1997",
    "AGTAGATGCTCCATAAAT_CCCAAATATC"=> "D11S4465",
    "GCAGTGTGAAAACAGACT_TTGCATTTTC"=> "D11S4952",
    "TCAAATATTCTCTCTCTC_TGTGAAATGT"=> "D11S2000",
    "GCAATTAAAGAGCTTATC_TCACTGAGTC"=> "D11S4464",
    "GCAGAGGACTTTGGAAGC_GCATTGCTGA"=> "D11S2367",
    "CAGTGGAAAGCAAAATGG_GGTATAATAT"=> "D12S1072",
    "AAATAATTTCTACCTCAC_TGTAACATCC"=> "D12S1300",
    "CAATGGGCAATAACTTCT_CACTTTACCT"=> "D12S395",
    "CCATCCTTCTTTTTATGA_GACCTTTTGA"=> "D12S2078",
    "GGACTTCTCAGCTTCCTT_ACAGAACTGA"=> "D13S800",
    "CATCCAGACTCCCCAGCT_CCCCCTTTTC"=> "D14S121",
    "GCTTAAGAGGATATCCTC_CCCAGACTTA"=> "D14S592",
    "CAAGATCATGTCACTGTA_ACATAAGCCT"=> "D14S617",
    "GCTATACCTTGTATTTAT_GAGGGTTGAG"=> "D15S643",
    "CAGAAAGCCAGGTCCCTT_CCAGGATACA"=> "D15S652",
    "CGAGTCAGGCGAGTTTTT_AATAGAAACA"=> "D15S816",
    "TGACAGCTACAGGCATGT_GCTATGGAAG"=> "D15S1515",
    "TGCTTTAAGACAGAAGAA_ACAACAAGTG"=> "D16S771",
    "CCCGGTTGTCAAAAGAGG_AAAAGAGAAA"=> "D16S2620",
    "CCCGCCTCAGGTAGGTGA_TCCATAGTCA"=> "D16S2621",
    "ACACAAATAAATATCCAT_TGTTTTATGG"=> "D17S1303",
    "GCATAGATGATAGTAAGG_CCAGTTATTC"=> "D17S2193",
    "CTGACTTAGCCTTGGAAG_CCCTCATGAA"=> "D17S968",
    "GGGCCTATGTTTCCAGTA_GCCAAATACT"=> "D18S1370",
    "ACCCAGTTAGACTTCACT_TGTGACTTGA"=> "D18S973",
    "GCTCTGCCACTAACTAGT_CTTCTGCTGG"=> "D18S843",
    "GGAAACCAAACTACAACG_AGGTCACCTA"=> "D18S542",
    "AAATATGCAAAGTATAGC_GCTTTATCAT"=> "D18S877",
    "TCTCCATAATCACATGAT_CAGAGAGACA"=> "D18S847",
    "GGGACTTGTCAGATTCCA_GCATTCTTTG"=> "D18S978",
    "AATAAATATATAGTTATA_CTTTATGAAG"=> "D18S851",
    "AGGGCCCCAATACAGGAG_AGTCTGTAGA"=> "D18S1364",
    "TCTCTCTCTCTTCATCCA_CCTGTGTTGT"=> "D18S1371",
    "ACTAATTGATTACTATAG_CCCAGATAAA"=> "D20S473",
    "AAAAGTGCATGCACTGGA_GGCATTCTTC"=> "D20S603",
    "AGAAAGGCAGATAGACAG_CCATCTGGGG"=> "D20S162",
    "TCGACTGACAATATTTCA_ACATTGTAAA"=> "D20S1085",
    "CATTCCAGCCTTGCAAAA_TCTTCTACTT"=> "D20S468",
    "TCATGGCACTTGTATACC_TAGAGGTGGC"=> "D20S1082",
    "ATCTCAATTTGAGTTTGA_TCACCTACAT"=> "D22S685",
    "CGGCAAGACCCTGTTTTG_GCCAGCTTTT"=> "D22S417",
    );
my %len1_0= (
    "CAACTCTTCCTAGATCTC_GACTCTGTAT"=> "WHAD_001",
    "CAGAATGCACCGCTCTGA_CATTAACCTA"=> "WHAD_002",
    "TAGCATGCAAAGGAGAAC_GAGGAAAATC"=> "WHAD_003",
    "ATTTTGAGCTAAAGGAAG_CTTTTAGGCA"=> "WHAD_004",
    "TCCATAATGTAAGACCAA_AATGAGCAAA"=> "WHAD_005",
    "CTCTCCCAATCTATATCT_GACTGTTCAA"=> "WHAD_006",
    "GAGGTGAGATTGCTCCAC_CTGCCATAAT"=> "WHAD_007",
    "AATCACACACCCATACAC_GAGGAAAGTG"=> "WHAD_008",
    "TAACTCCCAAATCCAAGA_GAGGATGTTG"=> "WHAD_009",
    "GTGTGTGTAGTGTGTGAT_CACACTCACC"=> "WHAD_010",
    "CTACCATATTGAAAAGTG_CAAAAGTAAT"=> "WHAD_011",
    "ACTAGCTCATGAAGGGAT_TCTCAATAGA"=> "WHAD_012",
    "GGGTAGATGGGGTGGGTT_GCTATGTGAT"=> "WHAD_013",
    "TCCAACTGTCTATGATAA_GGTGTGATTT"=> "WHAD_014",
    "GCTGTTTTATTCTAGCAT_GTGAATGCCC"=> "WHAD_015",
    "ACAGGTAGGATTTTTGAG_CTGGCATTCA"=> "WHAD_016",
    "TTTCATTCCCTTTTTATT_GTGGAGGCTG"=> "WHAD_017",
    "TGAGTGGAGATCGCACCA_TCAGCAGCTT"=> "WHAD_018",
    "ACACTGAAGCAAAAGTTT_TTCCTCTTTT"=> "WHAD_019",
    "ACCTTGGAAGTATAAACC_AAAACAAAAC"=> "WHAD_020",
    "AGGGAAGGAATATAGGTA_TGGGTGTATC"=> "WHAD_021",
    "TATCTTCCAGGGGCTTCT_AGAGGGAAAC"=> "WHAD_022",
    "TCGAATGTAATGTAATCG_GTCCATTAGA"=> "WHAD_023",
    "GGTTGATCTGAAATTCAA_CTGTGGTTCC"=> "WHAD_024",
    "AGACTACGCAGAAATCAA_GTGGCAGAGT"=> "WHAD_025",
    "GTCCTGAAACAAGTAACT_TTATTCAGTT"=> "WHAD_026",
    "GTTCTGGTTTTGTCTCTG_GACAGATGAC"=> "WHAD_027",
    "GGGCACATTTTTCTCACT_GGTTCAAGTC"=> "WHAD_028",
    "CACACACACACACACACA_GAGACTGCAC"=> "WHAD_029",
    "CGATGGTCATAGAGACTC_GAAGATAAGA"=> "WHAD_030",
    "CCTTCTCTGTAGTTTTTA_TCAAGGAGTT"=> "WHAD_031",
    "ACCCAGGTAAGTTTTTGG_GAGGTTGCAG"=> "WHAD_032",
    "CTGTCACGAGTTTCATCC_ACAAAACAAA"=> "WHAD_033",
    "AGAAATGGAAGCATTTTA_AGCCTGGTTA"=> "WHAD_034",
    "GGCTCCACAATCAAATGA_ATGTATCCAG"=> "WHAD_035",
    "TGTGGAAAATACTGTCTA_GGTGACCAAA"=> "WHAD_036",
    "TCTAGTTAGTTCTGTCCC_AGAGGGACAG"=> "WHAD_037",
    "TTGTATTTTGTTTAACGT_GGTACCATGT"=> "WHAD_038",
    "CCTGTGGATATCGACAGT_GGCTACAGAG"=> "WHAD_039",
    "GAGCCAGGTCTAATAGTG_GACAGTGACA"=> "WHAD_040",
    "ACTGAGGGCTTCATAGAC_AACCTATTTA"=> "WHAD_042",
    "TCCTAAATTTGATACGTT_CCTGGAGAAC"=> "WHAD_044",
    "GCCAGCGAGCATTTCACT_GCATGGGATA"=> "WHAD_045",
    "ACCTTTTTCTTCACAACC_GCTCAACATC"=> "WHAD_046",
    "ATTGGTCTGGAAACGAAC_TCCAGCTCCT"=> "WHAD_047",
    "AGTATCACAGGGGGTTTT_TGCACCTTCT"=> "WHAD_048",
    "TGAAATAGGCTAGCATGA_AGCCAGATTA"=> "WHAD_049",
    "AGACATTTGAGTTCTTTG_ATTCCACTCC"=> "WHAD_050",
    "CTGCTTGATCTCACCTAT_TTGACAAACA"=> "WHAD_051",
    "CTATGGAAATGCATAAGC_CTAATCCTAC"=> "WHAD_052",
    "ATATTGCTATTTGGTCAC_CAGCAAATTA"=> "WHAD_053",
    "AATGTGAAATAATGAAAT_GCCCCGAGTA"=> "WHAD_054",
    "ATTAATTGGTGTTGTAGA_AGAATCTCCA"=> "WHAD_055",
    "CATTCTTCTTGTGGGAAA_GGACTTTGAA"=> "WHAD_056",
    "GGCAACAGTAGCCAATTA_CCTTCAAGAG"=> "WHAD_057",
    "TTGTACCTCTACCTGATA_AAGGCATTTT"=> "WHAD_058",
    "TAGAACTCGAAAATGGGT_GTCGGATGTC"=> "WHAD_059",
    "TTCTGTGGTTTGTGAGAC_CATAAATGCT"=> "WHAD_060",
    "GTGATAATGACCAGTGAA_TATTCATAGT"=> "WHAD_061",
    "GGAAATGTGTTGGGCAGA_AAGTCCAGTA"=> "WHAD_062",
    "TCAGGTTGTGAAAAGTTC_ACTGAGAAAT"=> "WHAD_063",
    "TGATGATTCCAATCGAGA_TGGAATCATC"=> "WHAD_064",
    "ACTGTTCTGGAATGGAGA_CTGTAGTTGA"=> "WHAD_065",
    "CTGACGGTGGCTGGTCTA_GAGATGTTCT"=> "WHAD_066",
    "ATCGCCAGCCTAATTAGT_ACCATAGTCC"=> "WHAD_067",
    "ATCTCCTTTGCAGATAGA_ATCTAGGCAG"=> "WHAD_068",
    "AACTTATGTGTAAACTGG_TGGGAAACAG"=> "WHAD_069",
    "TTCTTTTCCCTTAGAGAT_ATTAACTGCT"=> "WHAD_070",
    "ACATGCATGTCCTCTTAA_TGGCAGAACG"=> "WHAD_071",
    "TAAAATTTTCCAATTGGC_ATCTCTCCCA"=> "WHAD_072",
    "CTTATGTGCTAAAGCCAG_TTTTTCTCCC"=> "WHAD_073",
    "TGAGACCCTGTCACCAGA_ACAGGAATTC"=> "WHAD_074",
    "AAATGTGTTTATGTCAGA_CCCACCCAAG"=> "WHAD_075",
    "CATTGGCCAGCAGCTCCT_GACCGAACTA"=> "WHAD_076",
    "TCGTATAAAAACTAGACA_GAGAATATCC"=> "WHAD_077",
    "GCATTCGTCTCACAAAGT_CACAATAGGA"=> "WHAD_078",
    "GCATTCGTCTCACAAAGT_CACAATAGGA"=> "WHAD_078",
    "CTCTGCGTCCTTTCTTAT_GGGCTCACCA"=> "WHAD_079",
    "TTTCCGGGTCTGCAGGAA_GAGCCAGAAG"=> "WHAD_080",
    "CCACACGCAGCTAATTTT_ACTCCAGCCC"=> "WHAD_081",
    "CAAGAGCAAAATCCCGTG_AGCTAAAAGA"=> "WHAD_082",
    "CACTGCACTCCACTGTGG_CACTGGCCTC"=> "WHAD_083",
    "TCATACAGTATGCTAGGT_CAGTCAGTAA"=> "WHAD_084",
    "CCACCATTTGTATTTCGA_AAGTTGCAGT"=> "WHAD_085",
    "TCTACTGTTTCCATGCTG_TAAAACTTCC"=> "WHAD_087",
    "TGTTGGGGAGCAGAATTA_GACAGACAGA"=> "WHAD_088",
    "TTCAAGACACCATCAGCA_AATGAAGGAA"=> "WHAD_089",
    "AGCCACTGTACATGGCAT_TGGAACAGGT"=> "WHAD_092",
    "CTCAGTTCCTGATTTTTC_GCTCCAGGAG"=> "WHAD_093",
    "CAGCAGGTAGTATGCCCA_GGATGAGCTT"=> "WHAD_094",
    "ACTAAGAGAGCCGCTAAA_GGGTGACAGC"=> "WHAD_095",
    "ACAAGAACAAACTAAACC_ACCCTTGAAA"=> "WHAD_096",
    "AGAAGTCCAAAGACAGAA_AGTCCTGAGG"=> "WHAD_097",
    "AAAAATCCTGATACTTGG_TTGATTGCAC"=> "WHAD_098",
    "GACACCTTTGTGCCAGAT_TGCCTCAAGC"=> "WHAD_099",
    "CTCCAACCAATGCCTAGC_GTGACATTTG"=> "WHAD_100",
    "GGGGAAGTCACCTAGCCT_CCTGTGATAG"=> "WHAD_101",
    "GAGGCTGCAGAGAATTAT_TCCAAATCCA"=> "WHAD_102",
    "AGTTTTGAAAATGTGCTA_AAACAGACAT"=> "WHAD_103",
    "GAAGCAAGCTCACCGACG_GTTCCTCAGG"=> "WHAD_104",
    "AGCTGGAAACCAAAGAAT_GCTTCTACAT"=> "WHAD_105",
    "AAAAGAGAGAATACTGAA_TCTCCTGACT"=> "WHAD_106",
    "GTCTCTGATCTCTTATCC_AGACATTCCC"=> "WHAD_107",
    "CTGGCCTTTGGTTTAACT_GTCTGAGCCT"=> "WHAD_108",
    "CAAAGCAAGGTCGTAAGT_AGGCTTTGAA"=> "WHAD_109",
    "GCCAGTAGAGAGATCTAA_CTCAGCCCAC"=> "WHAD_110",
    "GCTCTAATTCAAAGGACG_GTCAGATTCA"=> "WHAD_111",
    "CTGCACGGGACCAACACA_TCTTCAAAGA"=> "WHAD_112",
    "TTATTTTTGCCCTTGTAC_CTGCTTTCAG"=> "WHAD_113",
    "CAAGTTGAGCCTGACCTG_CACAGAGACT"=> "WHAD_114",
    "GGAACTGAGATGGCGTCA_AAACACGTAG"=> "WHAD_115",
    "TTTACACTTTCTTTGTGC_CGGATCTGGG"=> "WHAD_116",
    "GGTCCATGAAGCCATCTC_TCAAATTGTC"=> "WHAD_117",
    "CCTTTGAGGCAACAAACA_GCCCAGGCAT"=> "WHAD_118",
    "GGGCCATAGTTCTCATCA_CCTGGGTAAC"=> "WHAD_119",
    "AGATAAAATACACAACCC_TGGGTGACAG"=> "WHAD_121",
    "CATCAAATGACCCACTTC_CAAAGTGAGA"=> "WHAD_122",
    "ACTTTGATTTAGTCCCTC_TTCTCAGGTG"=> "WHAD_123",
    "TGCAAGAATCAGTGAAAA_AACAATGAAG"=> "WHAD_124",
    "CAGTAGCCTGTGCATAGG_AGTGGGACTC"=> "WHAD_125",
    "ACTTCCTCAATATGATAT_AGGTCTATTA"=> "WHAD_126",
    "GTTGAAGTGAGTGCCAAG_TCACTCTATA"=> "WHAD_127",
    "CTGGATCTCATATGTTCT_AAAACATCCT"=> "WHAD_128",
    "GTGAAAGATGTAAGGTGT_GGGCAAAGAA"=> "WHAD_129",
    "GATGGGGTTGGATTCTTA_TCAGTCATGT"=> "WHAD_130",
    "ACTACACCTGGTTTGTTT_ACTTTGAGAG"=> "WHAD_131",
    "TAAGGCCTCTGACACACT_CATTCTCAGC"=> "WHAD_132",
    "AGACTTTTTGGTTGGAAT_CGACAGCCAG"=> "WHAD_133",
    "CCAGCAAAAGGAACAAAA_GGGAGACAGA"=> "WHAD_134",
    "TGATTTCCATTACTTCCC_GTAATGTGAG"=> "WHAD_135",
    "GGGCCTCAGAGCAAGACT_CAGGAAGCAG"=> "WHAD_136",
    "CTTCAACTTATGAGGAGC_TTCACACACA"=> "WHAD_137",
    "CTAGAGTCCAGTTTCATG_GCAGTTATAT"=> "WHAD_138",
    "GTTGTCTGGGGCAGTGGT_GCCTCAGCCT"=> "WHAD_139",
    "TCTTCTTTGTTCTTGTCT_AGTGTGATTT"=> "WHAD_140",
    "TTCTATTTCTTTGCTTGT_GGTCTTCCAC"=> "WHAD_141",
    "TGTAAAATATGTTTAAGT_TGTTAGGACT"=> "WHAD_142",
    "TGCAGTAGATCCACATCC_TTGTAGAATT"=> "WHAD_143",
    "TATCTCAGTCCTGTGGAA_ACCCAGTCTG"=> "WHAD_144",
    "TCTTTATGCCTCTGAGTG_AAGCCTTGCC"=> "WHAD_145",
    "CTCTTTAGGCTGTTTCCA_TCTCCAAAAG"=> "WHAD_146",
    "GGAAGCAATTGTATCTCT_GCAAGCAGCT"=> "WHAD_149",
    "CTCGCTCTCTCCATTCAG_CAATGGGAGG"=> "WHAD_150",
    "AACAAAGCCAAAGCCAAA_GTGGGTAGAC"=> "WHAD_151",
    "GAAGTGTTATGGGTCCAG_CTTCCTTCTG"=> "WHAD_152",
    "GCTTTTATTTTTGCCTTC_ACCAAAAAGT"=> "WHAD_153",
    "AGACAGTTTACAAAACAT_AGATAGACAT"=> "WHAD_154",
    "ATTTGTAAAGTCACTGTC_CTGGGCATCC"=> "WHAD_155",
    "TGGCCAATAAATAGGTCA_TGACATTCAC"=> "WHAD_156",
    "TCTCTCTCTCTCTCTCTC_ATTCAGTGTT"=> "WHAD_157",
    "TTCTTATTTCTCCCAGGC_TGTGGCTATG"=> "WHAD_158",
    "AGTTAGAGGCACTAAGAC_GTGCTTGTGT"=> "WHAD_159",
    "GCAAGAAGGCTTTAGAAA_GATCTGTGAT"=> "WHAD_160",
    "GAAATGTCACCTGCTCAG_TTATAGCCAT"=> "WHAD_161",
    "TTATGTGTACATATATGA_ATAAACTTCC"=> "WHAD_162",
    "TAAGCCATTGTTTCTTGA_GAGCCATGAT"=> "WHAD_163",
    "AACAAAGAAGCAGTTGGA_ATTCTGGACT"=> "WHAD_164",
    "GGTCACTACAGAAAGAGG_ACAAAACGAA"=> "WHAD_165",
    "CAATGCACAATAGTTACA_AGGTCATCAC"=> "WHAD_166",
    "CAGACCCTTGGAAAGTGC_CAACACAGCC"=> "WHAD_167",
    "TAATAATTCTCTTGCAAG_GCTTTCCCCT"=> "WHAD_168",
    "TTAATGACAAAGGCTTGG_CTCCAGAAAC"=> "WHAD_169",
    "CAGCCACTAATACATTGT_GTTTGTGATA"=> "WHAD_170",
    "TGCTTGCATTAAAGACAC_AGTTATTCAA"=> "WHAD_171",
    "GTGATGTGGGGAATAAAA_TGACATTAAC"=> "WHAD_172",
    "TAGCCTCTTTGCTCTCTC_AAAATAGAAA"=> "WHAD_173",
    "CAGTGCAGCCTGGAGACT_GACCTTTAGG"=> "WHAD_175",
    "AGGCTCTTATTACATCAG_CTCCCTTTGA"=> "WHAD_176",
    "TCAAGTTTCAACGTTCAG_GGGAGGAGAG"=> "WHAD_177",
    "GCACACCCCCTCCCTTTT_CTGGGCCTGC"=> "WHAD_178",
    "TGGCCAAATCCCTCTCAC_CCCCAAAGAA"=> "WHAD_179",
    "ACCTGAGATAACTTGATT_AATTGAGCCC"=> "WHAD_180",
    "CCTAAGAGGACCACCCAG_TGGATATGCC"=> "WHAD_181",
    "AAGAGCGGCTGTCTCAGA_GCAAATGCAA"=> "WHAD_182",
    "AGCAAAGACATAGAATAC_GCAATCACCG"=> "WHAD_183",
    "AACAACCCACACAATTTA_CTGGATGACA"=> "WHAD_184",
    "CCATAGCCCCTGATAGGA_TCCTCCATTT"=> "WHAD_185",
    "CAGGAGCTTTTCTTTTCT_TGCTGAAAGA"=> "WHAD_186",
    "TGACAGTCTTATCACCCA_GGTGAGAGAG"=> "WHAD_187",
    "CTAGACACCTACCTCATC_GGTAACAGAC"=> "WHAD_189",
    "GAGTGTAAGCATGGCACC_TTTAGACTGG"=> "WHAD_190",
    "TGATGATTACCAGGTAAA_CACTGTGGGC"=> "WHAD_191",
    "GGATGATTTGCTCCAAAG_CCATTCACCA"=> "WHAD_192",
    "TCCTAGGTAAACTTGAAA_AAATGAAATG"=> "WHAD_193",
    "TGTGGCAAGAGGTAGAGA_TTTCAACAGA"=> "WHAD_194",
    "AGTCTCTCAGATGGCATT_TCCAAATATC"=> "WHAD_195",
    "TCTGAAACTGATTCTGTT_ATTTAAGAGG"=> "WHAD_196",
    "TAAACCTGTAGTAGAAGT_TATTTGGTAG"=> "WHAD_197",
    "TTGCAGAGAGCTTGGAGA_TGTAAACATC"=> "WHAD_200",
    "AGTCTGTGTCTTTTTCCT_GTTTGCCTTC"=> "WHAD_201",
    "AATCGCTTCTCTGAATAC_ATCTTGCAAG"=> "WHAD_202",
    "AAGTTTGTGCAAAAAGGT_TTACCTAGAA"=> "WHAD_203",
    "TATTCAGGATTTGTCAAG_GCTATGACTA"=> "WHAD_204",
    "ACACTGCAATAGTTACTA_TCATCCAACA"=> "WHAD_205",
    "TGGAAAATGTGGGCTCGT_ATGAATTCTT"=> "WHAD_206",
    "GCTGATACAACACACTGG_TGGAAATGCC"=> "WHAD_207",
    "GCCATATAAAAACGCAGC_TGGTAAAATA"=> "WHAD_208",
    "ATTTTCTTTGCCTCATCA_TACTCGATTA"=> "WHAD_209",
    "TGATGAATCTGTTTAATC_ATTTATGATT"=> "WHAD_210",
    "TGTTATGGGTTATTCCAA_TCTCAGTTTC"=> "WHAD_211",
    "AGAGTCACTTGCTCTGTG_ACTTGGTAAA"=> "WHAD_212",
    "GTGGACTTTACGAACCAA_TTAAATCCTA"=> "WHAD_213",
    "CATGGGTCACTCAGTTAT_TGTGACCAGT"=> "WHAD_214",
    "GGTAGCCTGTTCAAATCC_ATCTCCCCTT"=> "WHAD_215",
    "GGATCAAATGGAGTTCCT_CCCTAGTAAG"=> "WHAD_216",
    "GCAAAGAAAAGCAGGAGA_AAACGTCTTA"=> "WHAD_217",
    "GAAATGGTTGGCTATTGA_CGAATGTGCT"=> "WHAD_218",

);
my @line;
my $header;
my $adapt = 0;
my $count;
my $effect = 0;
my @hash;
my %hash     = ();
my %hash_num = ();
my @prim;
my @hash1;
my %len;
my %len1;
die "Usage: perl $0 fastq1 fastq2  adapt out1 out2 primer rightmod > out\n"
  unless ( @ARGV == 7 );
open( IN1, "gzip -dc $ARGV[0]|" ) or die "Can not open file $ARGV[0]\n";
open( IN2, "gzip -dc $ARGV[1]|" ) or die "Can not open file $ARGV[1]\n";
open( ADAPT, ">>$ARGV[2].adapt.rate" )
  or die "Can not open file $ARGV[2].adatp.rate\n";
open( OUT1, ">$ARGV[3]" )        or die "Can not open file $ARGV[3]\n";
open( OUT2, ">$ARGV[4]" )        or die "Can not open file $ARGV[4]\n";
open( PRIM, ">$ARGV[5].primer" ) or die "Can not open file $ARGV[5].primer\n";

my $mod =  $ARGV[6];

foreach (keys %len_0){
    my @primers = split(/\_/,$_);
    my $leftseq = substr($primers[0],0,18);
    my $rightseq = substr($primers[1],0,$mod);
    $len{$leftseq.'_'.$rightseq} = $len_0{$_};
}

foreach (keys %len1_0){
    my @primers = split(/\_/,$_);
    my $leftseq = substr($primers[0],0,18);
    my $rightseq = substr($primers[1],0,$mod);
    $len1{$leftseq.'_'.$rightseq} = $len1_0{$_};
}

foreach ( keys %len ) {
    @hash = split( /\_/, $_ );
    $hash{ $hash[0] } = $len{$_} . '_F';
    $hash{ $hash[1] } = $len{$_} . '_R';
}
foreach ( keys %len1 ) {
    @hash1 = split( /\_/, $_ );
    $hash{ $hash1[0] } = $len1{$_} . '_F';
    $hash{ $hash1[1] } = $len1{$_} . '_R';
}

my $i = 0;
my $seqname1;my $seqname2;my $seq1;my $seq2;my $flag1;my $flag2;my $qual1;my $qual2;
while (  defined(my $v1 = <IN1>) and defined (my $v2 = <IN2> )) {

    chomp($v1,$v2);
    if ($i == 0){
        $seqname1 = $v1;
        $seqname2 = $v2;
    }
    if ($i == 1){
        $seq1 = $v1;
        $seq2 = $v2;
    }
    if ($i == 2){
        $flag1 = $v1;
        $flag2 = $v2;
    }
    if ($i == 3){
        $qual1 = $v1;
        $qual2 = $v2;
    }
    $i++;
    if ($i == 4) {
        $count++;
        my @fastq1 = ($seqname1,$seq1,$flag1,$qual1);
        my @fastq2 = ($seqname2,$seq2,$flag2,$qual2);
        my @header = split( /(\s+)/, $fastq1[0] );
        my $seq_a = substr( $fastq1[1], 0, 18 );
        my $seq_b = substr( $fastq2[1], 0, $mod );
        # print "@fastq1\n";
        if ( exists $hash{$seq_a} ) {
            $hash_num{ $hash{$seq_a} }++;
        }
        if ( exists $hash{$seq_b} ) {
            $hash_num{ $hash{$seq_b} }++;
        }
        if ( $v1 =~ 'GGGGGGGGGGGGGGGGGGGGGG' ) {
            $adapt++;
        }
        elsif ( exists $len{ $seq_a . '_' . $seq_b } ) {
            $effect++;
            $hash_num{ $len{ $seq_a . '_' . $seq_b } }++;
            $header = '@' . $header[0] . '_' . $len{ $seq_a . '_' . $seq_b };
            print "$header\n$fastq1[1]\n$fastq1[2]\n$fastq1[3]\n";
        }
        else {
            #print OUT1 "@"."$header[0]\n$fastq1[1]\n$fastq1[2]\n$fastq1[3]\n";
            #print OUT2 "@"."$header[0]\n$fastq2[1]\n$fastq2[2]\n$fastq2[3]\n";
            if ( exists $len1{ $seq_a . '_' . $seq_b } ) {
                $effect++;
                $hash_num{ $len1{ $seq_a . '_' . $seq_b } }++;
                print OUT1 "@" . "$header[0]\n$fastq1[1]\n$fastq1[2]\n$fastq1[3]\n";
                print OUT2 "@" . "$header[0]\n$fastq2[1]\n$fastq2[2]\n$fastq2[3]\n";
            }
        }
        $i = 0;
    }
}
my ($sample) = ( $ARGV[0] =~ /^(.+)\_R1\.fastq.gz$/ );
print ADAPT "$sample\t$adapt\t$count\t"
  . $adapt / $count . "\t"
  . $effect / $count . "\n";
print PRIM "pos\t$sample" . '_'
  . "F\t$sample" . '_'
  . "R\t$sample" . '_' . "F_R\n";
foreach ( sort { $len{$a} cmp $len{$b} } keys %len ) {
    @prim = split( /\_/, $_ );
    if ( !exists $hash_num{ $len{$_} . '_F' } ) {
        $hash_num{ $len{$_} . '_F' } = 0;
    }
    if ( !exists $hash_num{ $len{$_} . '_R' } ) {
        $hash_num{ $len{$_} . '_R' } = 0;
    }
    if ( !exists $hash_num{ $len{$_} } ) {
        $hash_num{ $len{$_} } = 0;
    }

    print PRIM
"$len{$_}\t$hash_num{$len{$_}.'_F'}\t$hash_num{$len{$_}.'_R'}\t$hash_num{$len{$_}}\n";
}
foreach ( sort { $len1{$a} cmp $len1{$b} } keys %len1 ) {
    @prim = split( /\_/, $_ );
    if ( !exists $hash_num{ $len1{$_} . '_F' } ) {
        $hash_num{ $len1{$_} . '_F' } = 0;
    }
    if ( !exists $hash_num{ $len1{$_} . '_R' } ) {
        $hash_num{ $len1{$_} . '_R' } = 0;
    }
    if ( !exists $hash_num{ $len1{$_} } ) {
        $hash_num{ $len1{$_} } = 0;
    }
    print PRIM
"$len1{$_}\t$hash_num{$len1{$_}.'_F'}\t$hash_num{$len1{$_}.'_R'}\t$hash_num{$len1{$_}}\n";
}
