#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;
use Getopt::Long;
my %len = ( "ACGTTGGATGTCCACTTCTGTCTAG_ACGTTGGATGTCAGCCAAGAGATGC"=>"14727776",
"ACGTTGGATGGCTACATGGAAATGG_ACGTTGGATGTCTCACTTAGCACAT"=>"22750951",
"ACGTTGGATGTGTTTAGCCAACAGC_ACGTTGGATGGTGTGACCAGTCCTG"=>"21868672",
"ACGTTGGATGTATCCATTATCCTCT_ACGTTGGATGGACAGCTATAGAAAT"=>"14496407",
"ACGTTGGATGCAAGGTAGAAAAGCA_ACGTTGGATGAGTCACTTGCTCTGT"=>"21764674",
"ACGTTGGATGCAGAATGAACTAAGT_ACGTTGGATGCCAATACTAAGTTAA"=>"2850581",
"ACGTTGGATGTGTGCCCTTGAACCT_ACGTTGGATGCAGAATAATAACAGA"=>"14288981",
"ACGTTGGATGGCAATGAAGGTAGAA_ACGTTGGATGAGCATGATGTGCTGT"=>"2828196",
"ACGTTGGATGCTACTGATGCATAGA_ACGTTGGATGTGAGCCGAGATCAAG"=>"22749198",
"ACGTTGGATGTTCTAGTCAACTGCA_ACGTTGGATGCACAGACATAGTCAG"=>"8380264",
"ACGTTGGATGCCTCTGATGAATCAC_ACGTTGGATGTCTTACACACATAAG"=>"7746281",
"ACGTTGGATGAGACAGTCCTGGCTG_ACGTTGGATGGAAGGAGATAACCAT"=>"19335945",
"ACGTTGGATGGCATTTTAAGCTGAT_ACGTTGGATGAGATCTCCGTTACCC"=>"14968529",
"ACGTTGGATGGTTTAATATGTGCCA_ACGTTGGATGAACTTGCAGAGTTGC"=>"21757306",
"ACGTTGGATGCTTCCAGAGCCCTGC_ACGTTGGATGCCAATCCAATGACCC"=>"7546726",
"ACGTTGGATGAGAAGTGGAGAACTA_ACGTTGGATGCTACAAGTAGCTCAA"=>"14924869",
"ACGTTGGATGTCCCTCTTTGGAAAC_ACGTTGGATGGCAGATTTAGAGAAC"=>"14001232",
"ACGTTGGATGCATGTGATTTTTTTT_ACGTTGGATGGCTATTATTTAAATT"=>"6846802",
"ACGTTGGATGCTTTTTGCAGTGAGA_ACGTTGGATGGGGATTATAGCACTC"=>"16413861",
"ACGTTGGATGTTATGCTGAGCGTAG_ACGTTGGATGGCGGTGGGGTAATTT"=>"2975221",
"ACGTTGGATGTCTGCCTCACCACTA_ACGTTGGATGTCACCTCACTGTCTC"=>"8473059",
"ACGTTGGATGACAGGCACAAACAAC_ACGTTGGATGGGATAGCATGATTTG"=>"17763772",
"ACGTTGGATGTGACCAGCACTTGAT_ACGTTGGATGCTGGAGCTGACTCAG"=>"6945482",
"ACGTTGGATGGAGAGATACTTTTGA_ACGTTGGATGCAAACCCAGAAGGGT"=>"21716218",
"ACGTTGGATGTGGAAGCTAGCAGTA_ACGTTGGATGTTACCTTGATTCCAG"=>"21644600",
"ACGTTGGATGGAGATTATAACTAAA_ACGTTGGATGAACAGGGAGGGCTTA"=>"7618278",
"ACGTTGGATGCAAGCTGAGTTGAAA_ACGTTGGATGGAAGGAGGTGTTGCT"=>"14928001",
"ACGTTGGATGTCACGCATAACAACT_ACGTTGGATGGAAAGAAATCTGTAA"=>"7157789",
"ACGTTGGATGATTGTAAGAAAATGT_ACGTTGGATGCACTCTTATCTTGAT"=>"8159816",
"ACGTTGGATGAATCTACAACCAAGT_ACGTTGGATGTAGGGAGTGTTTATG"=>"17917402",
"ACGTTGGATGATACACCTCAAAGAG_ACGTTGGATGTAGAATTATTGAGCC"=>"6800409",
"ACGTTGGATGTGCCCCACTACACTG_ACGTTGGATGCAAAAGATCCGGTGA"=>"6756176",
"ACGTTGGATGGAACCCCAGCTACAC_ACGTTGGATGTTCTAGGTCTCAGAC"=>"14791279",
"ACGTTGGATGGGCTTTCTGGGAAAG_ACGTTGGATGCCATGAGAGGCCAAT"=>"8465550",
"ACGTTGGATGGTAGTCCTATAGATG_ACGTTGGATGGGATTCCTCCCAAAA"=>"17927014",
"ACGTTGGATGAAAGAACCGAGAGGC_ACGTTGGATGAGAGAGGCCCACCAA"=>"6932191",
"ACGTTGGATGTACATACATCTCTGG_ACGTTGGATGGTTTGTCCCCTTAAT"=>"6893926",
"ACGTTGGATGGGAACATGTCTCAAT_ACGTTGGATGGTGCTTCTAGCTTTT"=>"14127102",
"ACGTTGGATGTTCAGGCTTGCTATC_ACGTTGGATGAGTGTTCTCACTTCG"=>"8397316",
"ACGTTGGATGCCAAACTCTAGCACT_ACGTTGGATGTTCCAAAGAGAACTT"=>"16796672",
"ACGTTGGATGCCCACATTTTGTACA_ACGTTGGATGTTTGGTGCAGTTGAT"=>"19484305",
"ACGTTGGATGACCTGGGATGTAGAG_ACGTTGGATGTCTGTTGCCCAGGCT"=>"7078512",
"ACGTTGGATGGTGTAGCACTTCCCC_ACGTTGGATGAACTTACCTATGGGA"=>"8168239",
"ACGTTGGATGAGCACAATAACGCGT_ACGTTGGATGAGCAACACTGTAGAA"=>"6894836",
"ACGTTGGATGGCCTCCAAAAATGCT_ACGTTGGATGAGGAGAGAATCAACT"=>"7258483",
"ACGTTGGATGGCTCCCAAACAAATA_ACGTTGGATGATGTAGCAGTACGAG"=>"8580762",
"ACGTTGGATGGGAGGTTTTACTGTC_ACGTTGGATGCAATGCTAGAAGCTC"=>"2848491",
"ACGTTGGATGCAGCCAAAACAGAAT_ACGTTGGATGGTTTCATCTTTCAAA"=>"2815303",
"ACGTTGGATGTGACATCCTGAACCT_ACGTTGGATGTTTGGAGCTAATGAG"=>"22928068",
"ACGTTGGATGTGACTCTGGAATAAG_ACGTTGGATGCAAAAGGCCCTCATG"=>"8068096",
"ACGTTGGATGACTGTACAGCTAATG_ACGTTGGATGGGTGTTCAAATGCTA"=>"2890511",
"ACGTTGGATGCCTGTTTCAGGTACA_ACGTTGGATGCTCACAGTTACAAGT"=>"16933911",
"ACGTTGGATGTCCCATAATAGTAAT_ACGTTGGATGGTGAATTATGTCTTG"=>"8083640",
"ACGTTGGATGTCCACTTAGTATGGA_ACGTTGGATGGACTTTGGGTGATGA"=>"6897089",
"ACGTTGGATGGTTATACTTCACATG_ACGTTGGATGCTTGAGTAATCATTT"=>"8801983",
"ACGTTGGATGTCACACAACCTTTTG_ACGTTGGATGTCCCAATTCACTGTG"=>"23976986",
"ACGTTGGATGTTCTTGGGTCTGGAG_ACGTTGGATGCTCATAATGTCCTCA"=>"17511525",
"ACGTTGGATGAACTATGGACTGTAG_ACGTTGGATGCCTTCAGTTGACATA"=>"6655747",
"ACGTTGGATGAACTTTTTTCCACTC_ACGTTGGATGGCTCCAGAGTGGACT"=>"24397974",
"ACGTTGGATGTTAGGCCCTGTTCTT_ACGTTGGATGAAAGCAACCAGGTGC"=>"7674558",
"ACGTTGGATGTGCTGAAGAAACACT_ACGTTGGATGGATGCGAATGAGCAT"=>"6740428",
"ACGTTGGATGAACCAACAAAGTGGC_ACGTTGGATGTGAAACCTTGTGGTC"=>"7202706",
"ACGTTGGATGACATATACTGGGTGG_ACGTTGGATGCATGCCGGATTCCAT"=>"18045556",
"ACGTTGGATGCCACAATGAGACAAT_ACGTTGGATGAGCTGTCACAGATAT"=>"8633213",
"ACGTTGGATGGATAGCCACAGAGAT_ACGTTGGATGGCACAAAGGTGATGG"=>"8205381",
"ACGTTGGATGGGACCTTAAAAGAGA_ACGTTGGATGCAAAGAACCTGAAAA"=>"18404653",
"ACGTTGGATGTCACCTTTAGTGGGA_ACGTTGGATGTGTGTTACGACCTAT"=>"7825563",
"ACGTTGGATGCCACTCCTTCACAAA_ACGTTGGATGCCCAGTTTTAGCTAC"=>"17781145",
"ACGTTGGATGTGAGGCAATACCCTG_ACGTTGGATGCCAATTGAGGTACTT"=>"7347890",
"ACGTTGGATGCATTATTGGGAATAT_ACGTTGGATGAGATCTACAGAAGCA"=>"15953241",
"ACGTTGGATGTCCAACCTCAAGGTT_ACGTTGGATGCCTGAGATGGCCAGA"=>"28733210",
"ACGTTGGATGCTTTGGAATGCTGTA_ACGTTGGATGTTGAGTTGGTAAGGC"=>"17565364",
"ACGTTGGATGATTTGGTCTCAGTGG_ACGTTGGATGCAGTTCCTCAGCAAG"=>"16258362",
"ACGTTGGATGTTTTATAACAGCACT_ACGTTGGATGAGGAAGCTTTAGGGC"=>"19115647",
"ACGTTGGATGAGCTGGTAATGTTTG_ACGTTGGATGCCTTCATGTCATCAT"=>"2737185",
"ACGTTGGATGCTTGTCTCATTGCAA_ACGTTGGATGTGCCAGTGTTTCAGC"=>"14184331",
"ACGTTGGATGTTTCATATAGGCTGC_ACGTTGGATGGCTCATTCAGCAAAC"=>"17286406",
"ACGTTGGATGTCAGTTGATCACCCG_ACGTTGGATGTAAAACAACACGCAG"=>"6795544",
"ACGTTGGATGTCAGCAAAACCCCAG_ACGTTGGATGGTTTGACCTCCTAAG"=>"14097511",
"ACGTTGGATGCTTCTGAAAAGAAGC_ACGTTGGATGTCTCTCCTTGGGTTG"=>"8420152",
"ACGTTGGATGAATTCTACAGGAAGC_ACGTTGGATGGCCCAACTGTGATTA"=>"8522678",
"ACGTTGGATGTCATGGATTCACAGT_ACGTTGGATGCTTCTCCATCCACTG"=>"2737358",
"ACGTTGGATGCCATCTTTCACTGGC_ACGTTGGATGGGGAACAGAATGTAG"=>"8505900",
"ACGTTGGATGCAGGAAATCAGTTTG_ACGTTGGATGACCTTCACCAAGAAG"=>"2805744",
"ACGTTGGATGTCAGCCTTCTTCTGG_ACGTTGGATGAGCTTCTCCTCTGGA"=>"21751440",
"ACGTTGGATGTGCAGCCTTGTGATC_ACGTTGGATGGGCATGTAATCATTC"=>"4078217",
"ACGTTGGATGTTCAGGCTTTCAATC_ACGTTGGATGCCTCAAACTTGTCTC"=>"8526023",
"ACGTTGGATGGTTTGCCTTTTTTCC_ACGTTGGATGCGAGCACAACTATTC"=>"16931935",
"ACGTTGGATGTACAATCTGGTGAGG_ACGTTGGATGGGAATGCAGTTGGAA"=>"8524731",
"ACGTTGGATGTTTTATCTACTCAAC_ACGTTGGATGACACAGTTGAGGTGA"=>"21768133",
"ACGTTGGATGTGCTAGCAAAGTTGG_ACGTTGGATGCAAGCTACTACCTTA"=>"14851538",
"ACGTTGGATGTCCATGATCCCCAAT_ACGTTGGATGTTTATGTGAGGCAGA"=>"6913623",
"ACGTTGGATGCACATTGAACAAAAC_ACGTTGGATGCTCAAAATGCCTCTG"=>"14922924",
"ACGTTGGATGACATGCACCAAGCAC_ACGTTGGATGCTGGTTGTTGGTACC"=>"8259972",
"ACGTTGGATGTTCATTGACACCCTC_ACGTTGGATGGATTGGAATAGTGTG"=>"8500614",
"ACGTTGGATGACAATTAGGACAGGA_ACGTTGGATGAAAGACCTAACATGG"=>"6849372",
"ACGTTGGATGGCATACTCCTCATAG_ACGTTGGATGGGACAGTACTCAGAT"=>"18835005",
"ACGTTGGATGCCGTTAAGCAAAAAT_ACGTTGGATGGGAGAACAAAAAGAT"=>"21907538",
"ACGTTGGATGCACATACAGACTCTG_ACGTTGGATGGACCAACATTGAGTA"=>"21878072",
"ACGTTGGATGTCTTCAGCAACAGTA_ACGTTGGATGTCTCCTCTTCTATTG"=>"2734854",
"ACGTTGGATGTGCTCATATGTCTGT_ACGTTGGATGACCCCAGGCAAGACC"=>"7291534",
"ACGTTGGATGGGCAATGAAAAATCT_ACGTTGGATGCTTACAACACAGGGG"=>"21742158",
"ACGTTGGATGTTCACTTAGGCTTGG_ACGTTGGATGATCTGCCTTCCAACA"=>"2888203",
"ACGTTGGATGGCTTAAAAGAGATTG_ACGTTGGATGCCACCTAAAACTATT"=>"22744945",
"ACGTTGGATGCAACGCACTTTTGGT_ACGTTGGATGTCCTCAAATGCTCAG"=>"14838700",
"ACGTTGGATGGACCATATATTTTGC_ACGTTGGATGACTTGGAAAACAGGT"=>"21778998",
"ACGTTGGATGTCCTGGATTCAGCTC_ACGTTGGATGAAAGGTAGCTGCAAC"=>"21917313",
"ACGTTGGATGGTAATTAGTTTCTCA_ACGTTGGATGCAGCTTCATCCAACA"=>"15027529",
"ACGTTGGATGTTTCATCTCCAACCC_ACGTTGGATGACCCCTCAGTCTCTC"=>"14432928",
"ACGTTGGATGCTTTATTCCCTTTGT_ACGTTGGATGAGCTTCAGGAGGCTG"=>"21894058",
"ACGTTGGATGATCCCTGGCCAATAA_ACGTTGGATGGAAATATCAAGAAAC"=>"21753199",
"ACGTTGGATGGAAACCAAAGATACT_ACGTTGGATGATGTGGAGTAGTAGG"=>"21712855",
"ACGTTGGATGCTCCCAAAGTGCTGG_ACGTTGGATGAGAAGATTGCCCATC"=>"2888598",
"ACGTTGGATGGTGGGATTTTTTTAG_ACGTTGGATGCTTTCAAAACGTCTT"=>"22749853",
"ACGTTGGATGGAAAATAATAATTGA_ACGTTGGATGCATTTTTATCCCCCA"=>"14969634",
"ACGTTGGATGCAGGCTGGAAGAGTA_ACGTTGGATGCTTTGGGAGAAACAT"=>"2751678",
"ACGTTGGATGTGAGTTTGTGCAACC_ACGTTGGATGTCTCAGAGTTTTGTT"=>"21764458",
"ACGTTGGATGCATTGAACGTTTGAA_ACGTTGGATGCAGAACTGCAAAGAA"=>"21730257",
"ACGTTGGATGCAGTAAGTTCAGGCA_ACGTTGGATGCCCTCCCTCTCTCCT"=>"21730647",
"ACGTTGGATGGCATCTACCACTATG_ACGTTGGATGTGTCTGGTTCTCAAC"=>"21739646",
"ACGTTGGATGTGTCCATGTTTTCTG_ACGTTGGATGACTTAGATGGTCTCA"=>"22754671",
"ACGTTGGATGATTTACTTAGAGGCA_ACGTTGGATGTGAGCCCAAAAGTCT"=>"23550924",
"ACGTTGGATGTGAATCAGGCACATG_ACGTTGGATGCTACTGATACCTTTG"=>"15508706",
"ACGTTGGATGGATTTCCAGGGATAC_ACGTTGGATGATCTGATTTGATCTA"=>"2821786",
"ACGTTGGATGCCTGGACCTCAGAAG_ACGTTGGATGCAGTAACTCTAGGAG"=>"21867787",
"ACGTTGGATGCAAAAAACACGTTAA_ACGTTGGATGGTAAGCTTTCTACGG"=>"15018582",
"ACGTTGGATGTAGGTTGACCTGACA_ACGTTGGATGCTTTCATTTTAGGTA"=>"19096363",
"ACGTTGGATGGGGCAAATGTAAGTC_ACGTTGGATGTTCAACCTCTTGTTG"=>"15581983",
"ACGTTGGATGACACTGGCTTATCAT_ACGTTGGATGTTTCTTACAATTCAA"=>"15026424",
"ACGTTGGATGTCTGGCCTCTTGTAT_ACGTTGGATGTGACACAAGGCACCA"=>"2657176",
"ACGTTGGATGTTGGCCACTTAACAA_ACGTTGGATGCTGTCTACTCACCAG"=>"21733168",
"ACGTTGGATGAGGCAAGGTAAGAAC_ACGTTGGATGATCATAGGATGAGTC"=>"23307995",
"ACGTTGGATGAACACGTGCCTGGCA_ACGTTGGATGTATGCAAATGCAGAG"=>"2887824",
"ACGTTGGATGTTGAGGTTGCACAAA_ACGTTGGATGACACCAGAATCTAAC"=>"21764501",
 );
my @line;
my $header;
my $adapt;
my $count;
my $effect = 0;
my @hash;
my %hash     = ();
my %hash_num = ();
my @prim;
my @hash1;
die "Usage: perl $0 fastq1 fastq2  adapt out1 out2 > out\n"
  unless ( @ARGV == 6 );
open( IN1, "gzip -dc $ARGV[0]|" ) or die "Can not open file $ARGV[0]\n";
open( IN2, "gzip -dc $ARGV[1]|" ) or die "Can not open file $ARGV[1]\n";
open( ADAPT, ">>$ARGV[2].adapt.rate" )
  or die "Can not open file $ARGV[2].adatp.rate\n";
open( OUT1, ">$ARGV[3]" )        or die "Can not open file $ARGV[3]\n";
open( OUT2, ">$ARGV[4]" )        or die "Can not open file $ARGV[4]\n";
open( PRIM, ">$ARGV[5].primer" ) or die "Can not open file $ARGV[5].primer\n";

foreach ( keys %len ) {
    @hash = split( /\_/, $_ );
    $hash{ $hash[0] } = $len{$_} . '_F';
    $hash{ $hash[1] } = $len{$_} . '_R';
}

$/ = "\n@";
while ( defined( my $v1 = <IN1> ) and defined( my $v2 = <IN2> ) ) {

    #print $v1;
    $count++;
    my @fastq1 = split( /\n/,    $v1 );
    my @header = split( /(\s+)/, $fastq1[0] );
    my @fastq2 = split( /\n/,    $v2 );
    my $seq_a = substr( $fastq1[1], 0, 25 );
    my $seq_b = substr( $fastq2[1], 0, 25 );
    if ( exists $hash{$seq_a} ) {
        $hash_num{ $hash{$seq_a} }++;
    }
    if ( exists $hash{$seq_b} ) {
        $hash_num{ $hash{$seq_b} }++;
    }
    if ( $v1 =~ 'GGGGGGGGGGGGGGGGGGGGGG' ) {
        $adapt++;
    }
    elsif ( exists $len{ $seq_a . '_' . $seq_b } ) {
        $effect++;
        $hash_num{ $len{ $seq_a . '_' . $seq_b } }++;
        $header = '@' . $header[0] . '_' . $len{ $seq_a . '_' . $seq_b };
        #print "$header\n$fastq1[1]\n$fastq1[2]\n$fastq1[3]\n";
    }
    else {
        #print OUT1 "@" . "$header[0]\n$fastq1[1]\n$fastq1[2]\n$fastq1[3]\n";
        #print OUT2 "@" . "$header[0]\n$fastq2[1]\n$fastq2[2]\n$fastq2[3]\n";
    }
}

my ($sample) = ( $ARGV[0] =~ /^(.+)\_R1\.fastq.gz$/ );
print ADAPT "$sample\t$adapt\t$count\t" . $adapt / $count . "\t" . $effect / $count . "\n";
print PRIM "pos\t$sample" . '_' . "F\t$sample" . '_' . "R\t$sample" . '_' . "F_R\n";
foreach ( sort { $len{$a} cmp $len{$b} } keys %len ) {
    @prim = split( /\_/, $_ );
    if ( !exists $hash_num{ $len{$_} . '_F' } ) {
        $hash_num{ $len{$_} . '_F' } = 0;
    }
    if ( !exists $hash_num{ $len{$_} . '_R' } ) {
        $hash_num{ $len{$_} . '_R' } = 0;
    }
    if ( !exists $hash_num{ $len{$_} } ) {
        $hash_num{ $len{$_} } = 0;
    }

    print PRIM "$len{$_}\t$hash_num{$len{$_}.'_F'}\t$hash_num{$len{$_}.'_R'}\t$hash_num{$len{$_}}\n";
}

