args<-commandArgs(T)
b<-read.table(args[1],header=FALSE,sep="\t")
library(ggplot2)
#pdf("commandArgs(T).pdf",width=8,height=5)
pdfname<-paste(args[2],"pdf",sep=".")
pdf(pdfname,onefile=FALSE,width=8,height=5)
ggplot(data=b,aes(x=V1,y=V3 ,colour=V2,pch=V2,cex = 0.0001))+geom_point()+xlab('信号点')+ylab('相似度')+scale_color_manual(values =c('seagreen3','salmon'))+theme(axis.title.x =element_text(size=24),axis.title.y=element_text(size=24))+guides(colour=guide_legend(title='status'),pch=guide_legend(title='status'))
#pdfname<-paste(args[2],"pdf",sep=".")
#pdf(pdfname,onefile=FALSE)
#pdfname<-paste(args[2],"pdf",sep=" ")
#pdf("Heatmap.pdf",onefile=FALSE)
